<a href="https://colab.research.google.com/github/atul2017/Machine-Learning-Business-Cases/blob/main/Amazon_Product_Recommendation_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('amazon.csv')

Exploring the data like data dimension, information, null, counts, unique values etc.

In [ ]:
df.shape

(1465, 16)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   object
 1   product_name         1465 non-null   object
 2   category             1465 non-null   object
 3   discounted_price     1465 non-null   object
 4   actual_price         1465 non-null   object
 5   discount_percentage  1465 non-null   object
 6   rating               1465 non-null   object
 7   rating_count         1463 non-null   object
 8   about_product        1465 non-null   object
 9   user_id              1465 non-null   object
 10  user_name            1465 non-null   object
 11  review_id            1465 non-null   object
 12  review_title         1465 non-null   object
 13  review_content       1465 non-null   object
 14  img_link             1465 non-null   object
 15  product_link         1465 non-null   object
dtypes: object(16)
memory usage: 183.3+ KB

In [ ]:
df['user_name'].isnull().any()

np.False_

In [ ]:
df['user_name'].value_counts()

user_name
$@|\|TO$|-|,Sethu madhav,Akash Thakur,Burger Planet,Justice ⚖️,indrajyoti d.,Aditya Kumar,E.C.GEORGE               10
Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jaspreet singh,Khaja moin,Anand,S.ARUMUGAM                                8
Satheesh Kadiam,Pritom Chakraborty,Vishwa,Simranpreet Singh,Saptarshi,Amazon Customer,D.RAGHUL,Dharmendra kumar     8
ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Placeholder,BharanI,sonia,Niam                                            7
Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh chouhan,Ravi Siddan,Himanshu Goel,Udaykumar                           7
                                                                                                                   ..
Deepak B.,Azhar s.,Yogesh Rajput,Amit V.,Maneesha Biju,hassan,Purvesh,Shweha                                        1
Megha Gadiya,bharati boro,Ruma,Sai Raj Jaiswal,Kirti T Zanjale,Sinabail Mitra,Faizur rehman,Sanyam jain             1
Placeholder,Saddam Suthar,Priyanka Kasare,Geeta,Ahaan Zidaan,saransh,kaushal,Priyanka Mishra                        1
Anmol Khanna,G.l.sudhakar,Amazon Customer,manoj,Satya,Swarup Panday,Reyaansh Arora,neha keluskar                    1
ANURAG,Amazon Customer,Pallavi Jaiswal,Anshita,Pooja Bhargava,Manoj singh,Akanksha,Morpankh art gallery             1
Name: count, Length: 1194, dtype: int64

In [ ]:
df[df['user_name']=='Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jaspreet singh,Khaja moin,Anand,S.ARUMUGAM']

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,"Wayona Nylon Braided USB to Lightning Fast Charging and Data Sync Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini (3 FT Pack of 1, Grey)",Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables,₹399,"₹1,099",64%,4.2,"24,269","High Compatibility : Compatible With iPhone 12, 11, X/XsMax/Xr ,iPhone 8/8 Plus,iPhone 7/7 Plus,iPhone 6s/6s Plus,iPhone 6/6 Plus,iPhone 5/5s/5c/se,iPad Pro,iPad Air 1/2,iPad mini 1/2/3,iPod nano7,iPod touch and more apple devices.|Fast Charge&Data Sync : It can charge and sync simultaneously at a rapid speed, Compatible with any charging adaptor, multi-port charging station or power bank.|Durability : Durable nylon braided design with premium aluminum housing and toughened nylon fiber wound tightly around the cord lending it superior durability and adding a bit to its flexibility.|High Security Level : It is designed to fully protect your device from damaging excessive current.Copper core thick+Multilayer shielding, Anti-interference, Protective circuit equipment.|WARRANTY: 12 months warranty and friendly customer services, ensures the long-time enjoyment of your purchase. If you meet any question or problem, please don't hesitate to contact us.","AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBBSNLYT3ONILA,AHCTC6ULH4XB6YHDY6PCH2R772LQ,AGYHHIERNXKA6P5T7CZLXKVPT7IQ,AG4OGOFWXJZTQ2HKYIOCOY3KXF2Q,AENGU523SXMOS7JPDTW52PNNVWGQ,AEQJHCVTNINBS4FKTBGQRQTGTE5Q,AFC3FFC5PKFF5PMA52S3VCHOZ5FQ","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jaspreet singh,Khaja moin,Anand,S.ARUMUGAM","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1KD19VHEDV0OR,R3C02RMYQMK6FC,R39GQRVBUZBWGY,R2K9EDOE15QIRJ,R3OI7YT648TL8I","Satisfied,Charging is really fast,Value for money,Product review,Good quality,Good product,Good Product,As of now seems good","Looks durable Charging is fine tooNo complains,Charging is really fast, good product.,Till now satisfied with the quality.,This is a good product . The charging speed is slower than the original iPhone cable,Good quality, would recommend,https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/81---F1ZgHL._SY88.jpg,Product had worked well till date and was having no issue.Cable is also sturdy enough...Have asked for replacement and company is doing the same...,Value for money",https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/51UsScvHQNL._SX300_SY300_QL70_FMwebp_.jpg,https://www.amazon.in/Wayona-Braided-WN3LG1-Syncing-Charging/dp/B07JW9H4J1/ref=sr_1_1?qid=1672909124&s=electronics&sr=1-1
42,B07JW1Y6XV,"Wayona Nylon Braided 3A Lightning to USB A Syncing and Fast Charging Data Cable for iPhone, Ipad (3 FT Pack of 1, Black)",Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables,₹399,"₹1,099",64%,4.2,"24,269","[High Compatibility] : iPhone X/XsMax/Xr ,iPhone 8/8 Plus,iPhone 7/7 Plus,iPhone 6s/6s Plus,iPhone 6/6 Plus,iPhone 5/5s/5c/se,iPad Pro,iPad Air 1/2,iPad mini 1/2/3,iPod nano7,iPod touch and more apple devices.|[Fast Charge&Data Sync ] : It can charge and sync simultaneously at a rapid speed, Compatible with any charging adaptor, multi-port charging station or power bank.|[Durability] : Durable nylon braided design with premium aluminum housing and toughened nylon fiber wound tightly around the cord lending it superior durability and adding a bit to its flexibility.|[High Security Level ] : It is designed to fully protect your device from damaging excessive current.Copper core thick+Multilayer shielding, Anti-interference, Protective circuit equipment.","AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBBSNLYT3ONILA,AHCTC6ULH4XB6YHDY6PCH2R772LQ,AGYHHIERNXKA6P5T7CZLXKVPT7IQ,AG4OGOFWXJZTQ2HKYIOCOY3KXF2Q,AENGU523SXMOS7JPDTW52PNNVWGQ,AEQJHCVTNINBS4FKTBGQRQTGTE5Q,AFC3FFC5PKFF5PMA52S3VCHOZ5FQ","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jaspreet singh,Khaja moin,Anand,S.ARUMUGAM","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1KD19VHEDV0OR,R3C02RMYQMK6FC,R39GQRVBUZBWGY,R2K9EDOE15QIRJ,R3OI7YT648TL8I","Satisfied,Charging is really fast,Value for money,Product review,Good quality,Good product,Good Product,As of now seems good","Looks durable Charging is fine tooNo complains,Charging is really fast, good product.,Till now satisfied with the quality.,This is a good product . The charging speed is slower than the original iPhone cable,Good quality, would recommend,https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/81---F1ZgHL._SY88.jpg,Product had worked well till date and was having no issue.Cable is also sturdy enough...Have asked for replacement and company is doing the same...,Value for money",https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/41rB0DnVFmL._SX300_SY300_QL70_FMwebp_.jpg,https://www.amazon.in/Wayona-Braided-WN3LB1-Syncing-Charging/dp/B07JW1Y6XV/ref=sr_1_46?qid=1672909125&s=electronics&sr=1-46
80,B07LGT55SJ,"Wayona Usb Nylon Braided Data Sync And Charging Cable For Iphone, Ipad Tablet (Red, Black)",Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables,₹399,"₹1,099",64%,4.2,"24,269","[High Compatibility] : Compatible For iPhone X/Xs Max/Xr, Phone 8/8 Plus,Phone 7/7 Plus,Phone 6s/6s Plus,Phone 6/6 Plus,5/5s/5c/SE,Pad Pro,Pad Air 1/2,Pad mini 1/2/3,Pod nano7,Pod touch and more devices.|[Fast Charge&Data Sync ] : It can charge and sync simultaneously at a rapid speed, Compatible with any charging adaptor, multi-port charging station or power bank.|[Durability] : Durable nylon braided design with premium aluminum housing and toughened nylon fiber wound tightly around the cord lending it superior durability and adding a bit to its flexibility.|[High Security Level ] : It is designed to fully protect your device from damaging excessive current.Copper core thick+Multilayer shielding, Anti-interference, Protective circuit equipment.|[WARRANTY] 12-months warranty and friendly customer services, ensures the long-time enjoyment of your purchase. If you meet any question or problem, please don't hesitate to contact us. (10am - 7pm Working days)","AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBBSNLYT3ONILA,AHCTC6ULH4XB6YHDY6PCH2R772LQ,AGYHHIERNXKA6P5T7CZLXKVPT7IQ,AG4OGOFWXJZTQ2HKYIOCOY3KXF2Q,AENGU523SXMOS7JPDTW52PNNVWGQ,AEQJHCVTNINBS4FKTBGQRQTGTE5Q,AFC3FFC5PKFF5PMA52S3VCHOZ5FQ","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jaspreet singh,Khaja moin,Anand,S.ARUMUGAM","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1KD19VHEDV0OR,R3C02RMYQMK6FC,R39GQRVBUZBWGY,R2K9EDOE15QIRJ,R3OI7YT648TL8I","Satisfied,Charging is really fast,Value for money,Product review,Good quality,Good product,Good Product,As of now seems good","Looks durable Charging is fine tooNo complains,Charging is really fast, good product.,Till now satisfied with the quality.,This is a good product . The charging speed is slower than the original iPhone cable,Good quality, would recommend,https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81---F1ZgHL._SY88.jpg,Product had worked well till date and was having no issue.Cable is also sturdy enough...Have asked for replacement and company is doing the same...,Value for money",https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/41xmv3WPs7L._SX300_SY300_QL70_FMwebp_.jpg,https://www.amazon.in/Wayona-Braided-Syncing-Charging-iPhone/dp/B07LGT55SJ/ref=sr_1_89?qid=1672909128&s=electronics&sr=1-89
89,B07JH1C41D,"Wayona Nylon Braided (2 Pack) Lightning Fast Usb Data Cable Fast Charger Cord For Iphone, Ipad Tablet (3 Ft Pack Of 2, Grey)",Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables,₹649,"₹1,999",68%,4.2,"24,269","[High Compatibility] : iPhone X/XsMax/Xr ,iPhone 8/8 Plus,iPhone 7/7 Plus,iPhone 6s/6s Plus,iPhone 6/6 Plus,iPhone 5/5s/5c/se,iPad Pro,iPad Air 1/2,iPad mini 1/2/3,iPod nano7,iPod touch and more apple devices.|[Fast Charge&Data Sync ] : It can charge and sync simultaneously at a rapid speed, Compatible with any charging adaptor, multi-port charging station or power bank.|[Durability] : Durable nylon braided design with premium aluminum housing and toughened nylon fiber wound tightly around the cord lending it superior durability and adding a bit to its flexibility.|[High Security Level ] : It is designed to fully protect your device from damaging excessive current.Copper core thick+Multilayer shielding, Anti-interference, Protective circuit equipment.","AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBBSNLYT3ONILA,AHCTC6ULH4XB6YHDY6PCH2R772LQ,AGYHHIERNXKA6P5T7CZLXKVPT7IQ,AG4OGOFWXJZTQ2HKYIOCOY3KXF2Q,AENGU523SXMOS7JPDTW52PNNVWGQ,AEQJHCVTNINBS4FKTBGQRQTGTE5Q,AFC3FFC5PKFF5PMA52S3VCHOZ5FQ","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jaspreet singh,Khaja moin,Anand,S.ARUMUGAM","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1KD19VHEDV0OR,R3C02RMYQMK6FC,R39GQRVBUZBWGY,R2K9EDOE15QIRJ,R3OI7YT648TL8I","Satisfied,Charging is really fast,Value for money,Product review,Good quality,Good product,Good Product,As of now seems good","Looks durable Charging is fine tooNo complains,Charging is really fast, good product.,Till now satisfied with the quality.,This is a good product . The charging speed is slower than the original iPhone cable,Good quality, would recommend,https://m.media-amazon.com/images/I/81---F1ZgHL._SY88.jpg,Product had worked well till date and was having no issue.Cable is also sturdy enough...Have asked for replacement and company is doing the same...,Value for money",https://m.media-amazon.com/images/I/412fvb7k2FL._SX300_SY300_QL70_FMwebp_.jpg,https://www.amazon.in/Wayona-Braided-WN3LG2-Syncing-Charging/dp/B07JH1C41D/ref=sr_1_98?qid=1672909129&s=electronics&sr=1-98
106,B07JGDB5M1,"Wayona Nylon Braided 2M / 6Ft Fast Charge Usb To Lightning Data Sync And Charging Cable For Iphone, Ipad Tablet (6 Ft Pack Of 1, Grey)",Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables,₹449,"₹1,299",65%,4.2,"24,269","[High Compatibility] : Phone X/XsMax/Xr ,Phone 8/8 Plus,Phone 7/7 Plus,Phone 6s/6s Plus,Phone 6/6 Plus,Phone 5/5s/5c/se,Pad Pro,Pad Air 1/2,Pad mini 1/2/3,Pod nano7,Pod touch and more devices.|[Fast Charge&Data Sync ] : It can charge and sync simultaneously at a rapid speed, Compatible with any charging adaptor, multi-port charging station or power bank.|[Durability] : Durable nylon braided design with premium aluminum housing and toughened nylon fiber wound tightly around the cord lending it superior durability and adding a bit to its flexibility.|[High Security Level ] : It is designed to fully protect your device from damaging excessive current.Copper core thick+Multilayer shielding, Anti-interference, Protective circuit equipment.|[WARRANTY] 12-months warranty and friendly customer services, ensures the long-time enjoyment of your purchase. If you meet any question or problem, please don't hesitate to contact us. (10am - 7pm Working days)","AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBBSNLYT3ONILA,AHCTC6ULH4XB6YHDY6PCH2R772LQ,AGYHHIERNXKA6P5T7CZLXKVPT7IQ,AG4OGOFWXJZTQ2HKYIOCOY3KXF2Q,AENGU523SXMOS7JPDTW52PNNVWGQ,AEQJHCVTNINBS4FKTBGQRQTGTE5Q,AFC3FFC5PKFF5PMA52S3VCHOZ5FQ","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jaspreet singh,Khaja moin,Anand,S.ARUMUGAM","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1KD19VHEDV0OR,R3C02RMYQMK6FC,R39GQRVBUZBWGY,R2K9EDOE15QIRJ,R3OI7YT648TL8I","Satisfied,Charging is really fast,Value for money,Product review,Good quality,Good product,Good Product,As of now seems good","Looks durable Charging is fine tooNo complains,Charging is really fast, good product.,Till now satisfied with the quality.,This is a good product . The charging speed is slower than the original iPhone cable,Good quality, would recommend,https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/81---F1ZgHL._SY88.jpg,Product had worked well till date and was having no issue.Cable is also sturdy enough...Have asked for replacement and company is doing the same...,Value for money",https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/51UsScvHQNL._SX300_SY300_QL70_FMwebp_.jpg,https://www.amazon.in/Wayona-Braided-WN6LG1-Syncing-Charging/dp/B07JGDB5M1/ref=sr_1_119?qid=1672909129&s=electronics&sr=1-119
220,B07JH1CBGW,"Wayona Nylon Braided Usb Syncing And Charging Cable Sync And Charging Cable For Iphone, Ipad (3 Ft, Black) - Pack Of 2",Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables,₹649,"₹1,999",68%,4.2,"24,269","[High Compatibility] : iPhone X/XsMax/Xr ,iPhone 8/8 Plus,iPhone 7/7 Plus,iPhone 6s/6s Plus,iPhone 6/6 Plus,iPhone 5/5s/5c/se,iPad Pro,iPad Air 1/2,iPad mini 1/2/3,iPod nano7,iPod touch and more apple devices.|[Fast Charge&Data Sync ] : It can charge and sync simultaneously at a rapid speed, Compatible with any charging adaptor, multi-port charging station or power bank.|[Durability] : Durable nylon braided design with premium aluminum housing and toughened nylon fiber wound tightly around the cord lending it superior durability and adding a bit to its flexibility.|[High Security Level ] : It is designed to fully protect your device from damaging excessive current.Copper core thick+Multilayer shielding, Anti-interference, Protective circuit equipment.|[WARRANTY] 12-months warranty and friendly customer services, ensures the long-time enjoyment of your purchase. If you meet any question or problem, please don't hesitate to contact us (10am - 7pm Working days)","AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBBSNLYT3ONILA,AHCTC6ULH4XB6YHDY6PCH2R772LQ,AGYHHIERNXKA6P5T7CZLXKVPT7IQ,AG4OGOFWXJZTQ2HKYIOCOY3KXF2Q,AENGU523SXMOS7JPDTW52PNNVWGQ,AEQJHCVTNINBS4FKTBGQRQTGTE5Q,AFC3FFC5PKFF5PMA52S3VCHOZ5FQ","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jaspreet singh,Khaja moin,Anand,S.ARUMUGAM","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1KD19VHEDV0OR,R3C02RMYQMK6FC,R39GQRVBUZBWGY,R2K9EDOE15QIRJ,R3OI7YT648TL8I","Satisfied,Charging is really fast,Value for money,Product review,Good quality,Good product,Good Product,As of now seems good","Looks durable Charging is fine tooNo complains,Charging is really fast, good product.,Till now satisfied with the quality.,This is a good product . The charging speed is slower than the original iPhone cable,Good quality, would recommend,https://m.media-amazon.com/images/I/81---F1ZgHL._SY88.jpg,Product had worked well till date and was having no issue.Cable is also sturdy enough...Have asked for replacement and company is doing the same...,Value for money",https://m.media-amazon.com/images/I/41eHLj-wfGL._SX300_SY300_QL70_FMwebp_.jpg,https://www.amazon.in/Wayona-Braided-WN3LB2-Syncing-Charging/dp/B07JH1CBGW/ref=sr_1_241?qid=1672909136&s=electronics&sr=1-241
369,B07JW9H4J1,"Wayona Nylon Braided USB to Lightning Fast Charging and Data Sync Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini (3 FT Pack of 1, Grey)",Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables,₹399,"₹1,099",64%,4.2,"24,270","High Compatibility : Compatible With iPhone 12, 11, X/XsMax/Xr ,iPhone 8/8 Plus,iPhone 7/7 Plus,iPhone 6s/6s Plus,iPhone 6/6 Plus,iPhone 5/5s/5c/se,iPad Pro,iPad Air 1/2,iPad mini 1/2/3,iPod nano7,iPod touch and more apple devices.|Fast Charge&Data Sync : It can charge and sync simultaneously at a rapid speed, Compatible with any charging adaptor, multi-port charging station or power bank.|Durability : Durable nylon braided design with premium aluminum housing and toughened nylon fiber wound tightly around the cord lending it superior durability and adding a bit to its flexibility.|High Security Level : It is designed to fully protect your device from damaging excessive current.Copper core thick+Multilayer shielding, Anti-interference, Protective circuit equipment.|WARRANTY: 12 months warranty and friendly customer services, ensures the long-time enjoyment of your purchase. If you meet any question or problem, please don't hesitate to contact us.","AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBBSNLYT3ONILA,AHCTC6ULH4XB6YHDY6PCH2R772LQ,AGYHHIERNXKA6P5T7CZLXKVPT7IQ,AG4OGOFWXJZTQ2HKYIOCOY3KXF2Q,AENGU523SXMOS7JPDTW52PNNVWGQ,AEQJHCVTNINBS4FKTBGQRQTGTE5Q,AFC3FFC5PKFF5PMA52S3VCHOZ5FQ","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jaspreet singh,Khaja moin,Anand,S.ARUMUGAM","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1KD19VHEDV0OR,R3C02RMYQMK6FC,R39GQRVBUZBWGY,R2K9EDOE15QIRJ,R3OI7YT648TL8I","Satisfied,Charging is really fast,Value for money,Product review,Good quality,Good product,Good Product,As of now seems good","Looks durable Charging is fine tooNo complains,Charging is really fast, good product.,Till now satisfied with the quality.,This is a good product . The charging speed is slower than the original iPhone cable,Good quality, would recommend,https://m.media-amazon.com/images/I/81---F1ZgHL._SY88.jpg,Product had worked well till date and was having no issue.Cable is also sturdy enough...Have asked for replacement and company is doing the same...,Value for money",https://m.media-amazon.com/images/I/51UsScvHQNL._SX300_SY300_QL70_ML2_.jpg,https://www.amazon.in/Wayona-Braided-WN3LG1-Syncing-Charging/dp/B07JW9H4J1/ref=sr_1_38?qid=1672895755&s=electronics&sr=1-38
614,B07JW9H4J1,"Wayona Nylon Braided USB to Lightning Fast Charging and Data Sync Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini (3 FT Pack of 1, Grey)",Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables,₹399,"₹1,099",64%,4.2,"24,269","High Compatibility : Compatible With iPhone 12, 11, X/XsMax/Xr ,iPhone 8/8 Plus,iPhone 7/7 Plus,iPhone 6s/6s Plus,iPhone 6/6 Plus,iPhone 5/5s/5c/se,iPad Pro,iPad Air 1/2,iPad mini 1/2/3,iPod nano7,iPod touch and more apple devices.|Fast Charge&Data Sync : It can charge and sync simultaneously at a rapid speed, Compatible with any charging adaptor, multi-port charging station or power bank.|Durability : Durable nylon braided design with premium aluminum housing and toughened nylon fiber wound tightly around the cord lending it superior durability and adding a bit to its flexibility.|High Security Level : It is designed to fully protect your device from damaging excessive current.Copper core thick+Multilayer shielding, Anti-interference, Protective circuit equipment.|WARRANTY: 12 months warranty and friendly customer services, ensures the long-time enjoyment of your purchase. If you meet any question or problem, please don't hesitate to contact us.","AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBBSNLYT3ONILA,AHCTC6ULH4XB6YHDY6PCH2R772LQ,AGYHHIERNXKA6P5T7CZLXKVPT7IQ,AG4OGOFWXJZTQ2HKYIOCOY3KXF2Q,AENGU523SXMOS7JPDTW52PNNVWGQ,AEQJHCVTNINBS4FKTBGQRQTGTE5Q,AFC3FFC5PKFF5PMA52S3VCHOZ5FQ","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jaspreet singh,Khaja moin,Anand,S.ARUMUGAM","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1KD19VHEDV0OR,R3C02RMYQMK6FC,R39GQRVBUZBWGY,R2K9EDOE15QIRJ,R3OI7YT648TL8I","Satisfied,Charging is really fast,Value for money,Product review,Good quality,Good product,Good Product,As of now seems good","Looks durable Charging is fine tooNo complains,Charging is really fast, good product.,Till now satisfied with the quality.,This is a good product . The charging speed is slower than the original iPhone cable,Good quality, would recommend,https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/81---F1ZgHL._SY88.jpg,Product had worked well till date and was having no issue.Cable is also sturdy enough...Have asked for replacement and company is doing the same...,Value for money",https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/51UsScvHQNL._SX300_SY300_QL70_FMwebp_.jpg,https://www.amazon.in/Wayona-Braided-WN3LG1-Syncing-Charging/dp/B07JW9H4J1/ref=sr_1_33?qid=1672902996&s=computers&sr=1-33

In [ ]:
df.shape

(1465, 16)

In [ ]:
df['user_name'].nunique()

1194

In [ ]:
df['category'].nunique()

211

In [ ]:
df['user_id'].nunique()

1194

In [ ]:
df['product_id'].nunique()

1351

In [ ]:
df.isna().any()

product_id             False
product_name           False
category               False
discounted_price       False
actual_price           False
discount_percentage    False
rating                 False
rating_count            True
about_product          False
user_id                False
user_name              False
review_id              False
review_title           False
review_content         False
img_link               False
product_link           False
dtype: bool

In [ ]:
df.isnull().any()

product_id             False
product_name           False
category               False
discounted_price       False
actual_price           False
discount_percentage    False
rating                 False
rating_count            True
about_product          False
user_id                False
user_name              False
review_id              False
review_title           False
review_content         False
img_link               False
product_link           False
dtype: bool

There are multiple records for some of the product IDs.

In [ ]:
df['product_id'].value_counts()

product_id
B083342NKJ    3
B077Z65HSD    3
B09W5XR9RT    3
B09KLVMZ3B    3
B09NHVCHS9    3
             ..
B0BMVWKZ8G    1
B09LJ116B5    1
B08HV25BBQ    1
B09QS9X16F    1
B0B8CHJLWJ    1
Name: count, Length: 1351, dtype: int64

Let's see if the multiple records related to these product IDs are duplicate records.

In [ ]:
df[df['product_id']=='B07XLCFSSN']

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
36,B07XLCFSSN,"Amazonbasics Nylon Braided Usb-C To Lightning Cable, Fast Charging Mfi Certified Smartphone, Iphone Charger (6-Foot, Dark Grey)",Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables,₹899,"₹1,900",53%,4.4,"13,552","Fast Charge: When Used With An 18W Or Higher Usb-C Wall Charger With Power Delivery You Can Charge Your Iphone To 50% Battery In Just 30 Minutes - Supported Models Include Iphone 8, 8 Plus, X, Xs, Xr, Xs Max, 11, 11 Pro, 11 Pro Max, Ipads, And More. High-Speed Data Transfer: Up To 480 Mbps For Transferring Music, Movies, And More In Seconds|Durable Friendly Design: Built With Top Rated Materials And Tested To Withstand Up To X Bend Cycles And Features Textured Grooves On Connector Ends For Improved Grip|Certified Chip: Apple Mfi Certified Charging And Syncing Cable For Your Apple Devices With Improved Chipset To Ensure Full Compatibility|This Cable Is Not Compatible With Standard Usb Chargers / Laptop Ports. Works Only With Type C Adapters And Laptop Ports. Please Check The Port Of Your Adapter Before Buying The Cable.|Connector Type: Usb Type C","AF2IRSQZKMBGX44YDNUPYRHWXOZQ,AF6VSSXOI3Y4PZCNRJ3L27NCXPYA,AHQKC4MLLVOPBTKJFDBGTXFRKLYQ,AGX5ELLH3KJJ4CY2DJJOXDSOEI6Q,AGJ23TWSY6YFMAVSEAOAUEWO4QLQ,AFOHB4M2RWSUQ3SSZWPMD2FPH6PQ,AFVHKKOI25DAQSETPL7Z5W5SIVUA,AE55WJERHR4C7SEAIWX4JJHFSZBA","Wraith,Krishna Engineering,Kindle Customer,Deeps,Chintada Bhaskar Rao,FH,Vasudev,Done Chandra Mouli","R213ILI3XNVHQ0,R1LZN1V8UCR9IU,R1EBFTZINSJ0LG,R3BKR3VZ1U81LW,R5OJ20F8H5T8U,R1FKQR9LSBVLH2,R3R8UN7IQY7EIT,R2WBDNEW6HCVSH","Good,Worth to buy,Great value for price,Good product,Nice product.,Reliable and worth it!,Much more sturdy and durable than Apple cable,Good","Good budget mfi certified lightly cable for this price . Update usage review after 3 to 5 months .,Better than the original one in matter of robustness and durability. Better in prospect of charging . It is far better in durability from the original apple wire. Do not think more you can buy blindly worth to buy and it is mfi certified so you IOS device not damaged. But small negative point is packaging quality of the product.,The charger is a great carry on accessory while travelling without risking the original charger.Price is also very affordable and charging speed is very good with good adaptor or power bank.,Good product , can recommend all , only thing I see as issue is the material,, the cable threads peels off when stick to a Velcro materials. Other wise good product, charges very well like original,Nice,Reliable and worth it,The cable shipped in box made by Apple felt less sturdy and reliable after using one or two times and felt it would break more quickly at the lighting port and had to order Amazon basics cable which is miles better and apple MiFi certified,",https://m.media-amazon.com/images/I/3183iGEWksL._SX300_SY300_QL70_FMwebp_.jpg,https://www.amazon.in/AmazonBasics-Apple-Certified-Lightning-Charging/dp/B07XLCFSSN/ref=sr_1_40?qid=1672909125&s=electronics&sr=1-40
518,B07XLCFSSN,"Amazonbasics Nylon Braided Usb-C To Lightning Cable, Fast Charging Mfi Certified Smartphone, Iphone Charger (6-Foot, Dark Grey)",Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables,₹899,"₹1,900",53%,4.4,"13,552","Fast Charge: When Used With An 18W Or Higher Usb-C Wall Charger With Power Delivery You Can Charge Your Iphone To 50% Battery In Just 30 Minutes - Supported Models Include Iphone 8, 8 Plus, X, Xs, Xr, Xs Max, 11, 11 Pro, 11 Pro Max, Ipads, And More. High-Speed Data Transfer: Up To 480 Mbps For Transferring Music, Movies, And More In Seconds|Durable Friendly Design: Built With Top Rated Materials And Tested To Withstand Up To X Bend Cycles And Features Textured Grooves On Connector Ends For Improved Grip|Certified Chip: Apple Mfi Certified Charging And Syncing Cable For Your Apple Devices With Improved Chipset To Ensure Full Compatibility|This Cable Is Not Compatible With Standard Usb Chargers / Laptop Ports. Works Only With Type C Adapters And Laptop Ports. Please Check The Port Of Your Adapter Before Buying The Cable.|Connector Type: Usb Type C","AF2IRSQZKMBGX44YDNUPYRHWXOZQ,AF6VSSXOI3Y4PZCNRJ3L27NCXPYA,AHQKC4MLLVOPBTKJFDBGTXFRKLYQ,AGX5ELLH3KJJ4CY2DJJOXDSOEI6Q,AGJ23TWSY6YFMAVSEAOAUEWO4QLQ,AFOHB4M2RWSUQ3SSZWPMD2FPH6PQ,AFVHKKOI25DAQSETPL7Z5W5SIVUA,AE55WJERHR4C7SEAIWX4JJHFSZBA","Wraith,Krishna Engineering,Kindle Customer,Deeps,Chintada Bhaskar Rao,FH,Vasudev,Done Chandra Mouli","R213ILI3XNVHQ0,R1LZN1V8UCR9IU,R1EBFTZINSJ0LG,R3BKR3VZ1U81LW,R5OJ20F8H5T8U,R1FKQR9LSBVLH2,R3R8UN7IQY7EIT,R2WBDNEW6HCVSH","Good,Worth to buy,Great value for price,Good product,Nice product.,Reliable and worth it!,Much more sturdy and durable than Apple cable,Good","Good budget mfi certified lightly cable for this price . Update usage review after 3 to 5 months .,Better than the original one in matter of robustness and durability. Better in prospect of charging . It is far better in durability from the original apple wire. Do not think more you can buy blindly worth to buy and it is mfi certified so you IOS device not damaged. But small negative point is packaging quality of the product.,The charger is a great carry on accessory while travelling without risking the original charger.Price is also very affordable and charging speed is very good with good adaptor or power bank.,Good product , can recommend all , only thing I see as issue is the material,, the cable threads peels off when stick to a Velcro materials. Other wise good product, charges very well like original,Nice,Reliable and worth it,The cable shipped in box made by Apple felt less sturdy and reliable after using one or two times and felt it would break more quickly at the lighting port and had to order Amazon basics cable which is miles better and apple MiFi certified,",https://m.media-amazon.com/images/I/3183iGEWksL._SX300_SY300_QL70_ML2_.jpg,https://www.amazon.in/AmazonBasics-Apple-Certified-Lightning-Charging/dp/B07XLCFSSN/ref=sr_1_245?qid=1672895821&s=electronics&sr=1-245
839,B07XLCFSSN,"Amazonbasics Nylon Braided Usb-C To Lightning Cable, Fast Charging Mfi Certified Smartphone, Iphone Charger (6-Foot, Dark Grey)",Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables,₹899,"₹1,900",53%,4.4,"13,552","Fast Charge: When Used With An 18W Or Higher Usb-C Wall Charger With Power Delivery You Can Charge Your Iphone To 50% Battery In Just 30 Minutes - Supported Models Include Iphone 8, 8 Plus, X, Xs, Xr, Xs Max, 11, 11 Pro, 11 Pro Max, Ipads, And More. High-Speed Data Transfer: Up To 480 Mbps For Transferring Music, Movies, And More In Seconds|Durable Friendly Design: Built With Top Rated Materials And Tested To Withstand Up To X Bend Cycles And Features Textured Grooves On Connector Ends For Improved Grip|Certified Chip: Apple Mfi Certified Charging And Syncing Cable For Your Apple Devices With Improved Chipset To Ensure Full Compatibility|This Cable Is Not Compatible With Standard Usb Chargers / Laptop Ports. Works Only With Type C Adapters And Laptop Ports. Please Check The Port Of Your Adapter Before Buying The Cable.|Connector Type: Usb Type C","AF2IRSQZKMBGX44YDNUPYRHWXOZQ,AF6VSSXOI3Y4PZCNRJ3L27NCXPYA,AHQKC4MLLVOPBTKJFDBGTXFRKLYQ,AGX5ELLH3KJJ4CY2DJJOXDSOEI6Q,AGJ23TWSY6YFMAVSEAOAUEWO4QLQ,AFOHB4M2RWSUQ3SSZWPMD2FPH6PQ,AFVHKKOI25DAQSETPL7Z5W5SIVUA,AE55WJERHR4C7SEAIWX4JJHFSZBA","Wraith,Krishna Engineering,Kindle Customer,Deeps,Chintada Bhaskar Rao,FH,Vasudev,Done Chandra Mouli","R213ILI3XNVHQ0,R1LZN1V8UCR9IU,R1EBFTZINSJ0LG,R3BKR3VZ1U81LW,R5OJ20F8H5T8U,R1FKQR9LSBVLH2,R3R8UN7IQY7EIT,R2WBDNEW6HCVSH","Good,Worth to buy,Great value for price,Good product,Nice product.,Reliable and worth it!,Much more sturdy and durable than Apple cable,Good","Good budget mfi certified lightly cable for this price . Update usage review after 3 to 5 months .,Better than the original one in matter of robustness and durability. Better in prospect of charging . It is far better in durability from the original apple wire. Do not think more you can buy blindly worth to buy and it is mfi certified so you IOS device not damaged. But small negative point is packaging quality of the product.,The charger is a great carry on accessory while travelling without risking the original charger.Price is also very affordable and charging speed is very good with good adaptor or power bank.,Good product , can recommend all , only thing I see as issue is the material,, the cable threads peels off when stick to a Velcro materials. Other wise good product, charges very well like original,Nice,Reliable and worth it,The cable shipped in box made by Apple felt less sturdy and reliable after using one or two times and felt it would break more quickly at the lighting port and had to order Amazon basics cable which is miles better and apple MiFi certified,",https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/3183iGEWksL._SX300_SY300_QL70_FMwebp_.jpg,https://www.amazon.in/AmazonBasics-Apple-Certified-Lightning-Charging/dp/B07XLCFSSN/ref=sr_1_279?qid=1672903008&s=computers&sr=1-279

Data cleanup-
(1) Remove duplicate from dataset
(2) Remove rupees symbol from the price columns

In [ ]:
import re

def extract_symbol(text):
  """Remove the Rupees symbol from the discounted price"""
  cleaned_txt = re.sub(r'[^0-9.]', '', text)
  return cleaned_txt.strip()


df['discounted_price'] = df['discounted_price'].apply(extract_symbol).apply(pd.Series)

In [ ]:
import re

def extract_symbol(text):
  """Remove the Rupees symbol from the actual price"""
  cleaned_txt = re.sub(r'[^0-9.]', '', text)
  return cleaned_txt.strip()


df['actual_price'] = df['actual_price'].apply(extract_symbol).apply(pd.Series)

In [ ]:
df.head(2)

,actual_price,rating,rating_count,top_category,product_name_clean,about_product_final,content
0,1099,4.2,24269.0,Computers&Accessories,wayona nylon braided usb lightning fast charging cable,high xsmax nano7 appl fast charg data sync charg sync simultan rapid speed multi port charg station power bank durabl durabl nylon braid design premium aluminum hous toughen nylon fiber wound tightli cord lend superior durabl ad bit flexibl high secur level design fulli protect damag excess current copper core multilay shield anti interfer protect circuit equip ensur long time meet,wayona nylon braided usb lightning fast charging cable high xsmax nano7 appl fast charg data sync charg sync simultan rapid speed multi port charg station power bank durabl durabl nylon braid design premium aluminum hous toughen nylon fiber wound tightli cord lend superior durabl ad bit flexibl high secur level design fulli protect damag excess current copper core multilay shield anti interfer protect circuit equip ensur long time meet
1,349,4.0,43994.0,Computers&Accessories,ambrane unbreakable fast charging braided cable quick charge,smartphon tablet laptop support quick charg unbreak special braid outer rug interior bind ultra durabl cabl affect daili rough usag length length short typic cabl long cabl support maximum fast charg data transfer speed manufactur,ambrane unbreakable fast charging braided cable quick charge smartphon tablet laptop support quick charg unbreak special braid outer rug interior bind ultra durabl cabl affect daili rough usag length length short typic cabl long cabl support maximum fast charg data transfer speed manufactur

In [ ]:
import re

def extract_symbol(text):
  """Remove the Rupees symbol from the actual price"""
  test = str(text)
  number = float(test.replace(",", ""))
  return number


df['rating_count'] = df['rating_count'].apply(extract_symbol).apply(pd.Series)

In [ ]:
df.shape

(1465, 16)

In [ ]:
df = df.drop_duplicates(subset=['product_id', 'user_id','review_title'])

In [ ]:
df.shape

(1361, 16)

In [ ]:
df['category'].value_counts()

category
Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables                                          165
Electronics|Mobiles&Accessories|Smartphones&BasicMobiles|Smartphones                                                        68
Electronics|WearableTechnology|SmartWatches                                                                                 67
Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions                                                               60
Electronics|Headphones,Earbuds&Accessories|Headphones|In-Ear                                                                51
                                                                                                                          ...
Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|RotiMakers                                                        1
Home&Kitchen|Heating,Cooling&AirQuality|Parts&Accessories|FanParts&Accessories                                               1
Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|StandMixers                                                       1
Home&Kitchen|Heating,Cooling&AirQuality|Fans|PedestalFans                                                                    1
Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Vacuums&FloorCare|VacuumAccessories|VacuumBags|HandheldBags      1
Name: count, Length: 211, dtype: int64

Extracting the top category from the hirarchial category mentioned in category column and assign the top level in new column called top_category.

In [ ]:
df['top_category'] = df['category'].str.split('|').str[0]

/tmp/ipython-input-131-1298095924.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['top_category'] = df['category'].str.split('|').str[0]

In [ ]:
df.head(2)

,actual_price,rating,rating_count,top_category,product_name_clean,about_product_final,content
0,1099,4.2,24269.0,Computers&Accessories,wayona nylon braided usb lightning fast charging cable,high xsmax nano7 appl fast charg data sync charg sync simultan rapid speed multi port charg station power bank durabl durabl nylon braid design premium aluminum hous toughen nylon fiber wound tightli cord lend superior durabl ad bit flexibl high secur level design fulli protect damag excess current copper core multilay shield anti interfer protect circuit equip ensur long time meet,wayona nylon braided usb lightning fast charging cable high xsmax nano7 appl fast charg data sync charg sync simultan rapid speed multi port charg station power bank durabl durabl nylon braid design premium aluminum hous toughen nylon fiber wound tightli cord lend superior durabl ad bit flexibl high secur level design fulli protect damag excess current copper core multilay shield anti interfer protect circuit equip ensur long time meet
1,349,4.0,43994.0,Computers&Accessories,ambrane unbreakable fast charging braided cable quick charge,smartphon tablet laptop support quick charg unbreak special braid outer rug interior bind ultra durabl cabl affect daili rough usag length length short typic cabl long cabl support maximum fast charg data transfer speed manufactur,ambrane unbreakable fast charging braided cable quick charge smartphon tablet laptop support quick charg unbreak special braid outer rug interior bind ultra durabl cabl affect daili rough usag length length short typic cabl long cabl support maximum fast charg data transfer speed manufactur

In [ ]:
df['discounted_price'].isna().sum()

np.int64(0)

In [ ]:
df['actual_price'].isna().sum()

np.int64(0)

There is one product which has rating non-numeric.

Find out the top category "Home&Kitchen" mean rating and insert that in above product data. Since there is only one I am not over working to find median or mean based on how the ratings are spread in products. I don't see much impact.

In [ ]:
df['rating'] = pd.to_numeric(df['rating'], errors='coerce')

df.groupby('top_category')['rating'].mean()

top_category
Car&Motorbike            3.800000
Computers&Accessories    4.152770
Electronics              4.077823
Health&PersonalCare      4.000000
Home&Kitchen             4.040716
HomeImprovement          4.250000
MusicalInstruments       3.900000
OfficeProducts           4.309677
Toys&Games               4.300000
Name: rating, dtype: float64

In [ ]:
df.loc[df['product_id'] == 'B08L12N5H1', 'rating'] = 4

Verify the rating for this product is has been inserted.

Clean the product_name values.

In [ ]:
pd.set_option('display.max_colwidth', None)
df['product_name'].head(5)

0                                         Wayona Nylon Braided USB to Lightning Fast Charging and Data Sync Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini (3 FT Pack of 1, Grey)
1          Ambrane Unbreakable 60W / 3A Fast Charging 1.5m Braided Type C Cable for Smartphones, Tablets, Laptops & other Type C devices, PD Technology, 480Mbps Data Sync, Quick Charge 3.0 (RCT15A, Black)
2                                                                   Sounce Fast Phone Charging Cable & Data Sync USB Cable Compatible for iPhone 13, 12,11, X, 8, 7, 6, 5, iPad Air, Pro, Mini & iOS Devices
3    boAt Deuce USB 300 2 in 1 Type-C & Micro USB Stress Resistant, Tangle-Free, Sturdy Cable with 3A Fast Charging & 480mbps Data Transmission, 10000+ Bends Lifespan and Extended 1.5m Length(Martian Red)
4                                                                                             Portronics Konnect L 1.2M Fast Charging 3A 8 Pin USB Cable with Charge & Sync Function for iPhone, iPad (Grey)
Name: product_name, dtype: object

In [ ]:
#Convert the string to lower case
df['product_name'] = df['product_name'].str.lower()

In [ ]:
import re
import pandas as pd
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

STOP = set(ENGLISH_STOP_WORDS)

# domain-specific “stopwords” (noise in product titles)
NOISE = {
    "compatible", "with", "for", "and", "or", "other", "all", "devices", "device",
    "smartphone", "smartphones", "tablet", "tablets", "laptop", "laptops", "desktop", "pc",
    "function", "support", "supports", "technology", "series",
    "made", "india",
    "length", "long", "extended",
    "pack", "piece", "pieces", "set",
    "sync", "data",  # optional; remove if you want “data cable” similarity stronger
}

# colors/material-ish words that usually don’t help similarity
COLORS = {
    "black","grey","gray","white","red","green","blue","glossy","dark","iron","martian"
}

# keep connector terms unified
NORMALIZE = {
    "type-c": "typec",
    "usb-c": "typec",
    "typec": "typec",
    "type": "",      # helps remove stray 'type'
    "c": "",         # optional: prevents lonely “c” tokens
}

def clean_product_title(text: str) -> str:
    if pd.isna(text):
        return ""
    text = str(text).lower()

    # 1) remove bracketed/parenthetical chunks (often specs/colors/pack)
    text = re.sub(r"\(.*?\)", " ", text)

    # 2) remove OS/version compatibility blobs (windows 11/10/7..., mac os..., linux kernel..., xp)
    text = re.sub(r"\bwindows\s*\d+(\.\d+)?(\s*/\s*\d+(\.\d+)?)*\b", " ", text)
    text = re.sub(r"\bmac\s*os\s*\d+(\.\d+)?(-\d+(\.\d+)?)?\b", " ", text)
    text = re.sub(r"\blinux\s*kernel\s*\d+(\.\d+)?(-\d+(\.\d+)?)?\b", " ", text)
    text = re.sub(r"\bxp\b", " ", text)

    # 3) remove apple model/version list tokens
    text = re.sub(r"\b(iphone|ipad|ipod|ios)\b", " ", text)
    text = re.sub(r"\b(13|12|11|x|xs|max|xr|se|8|7|6|5|pro|mini|air)\b", " ", text)

    # 4) remove common measurement/spec patterns
    # numbers + units (80 cm, 1.5m, 3 foot, 32 inches, 2 meter, etc.)
    text = re.sub(r"\b\d+(\.\d+)?\s*(cm|mm|m|meter|metre|meters|metres|ft|feet|foot|inch|inches)\b", " ", text)
    # tech specs (60w, 3a, 18gbps, 480mbps, 1080p, 4k, 60hz, 4.4.3 etc.)
    text = re.sub(r"\b\d+(\.\d+)?\s*(w|a|gbps|mbps|hz)\b", " ", text)
    text = re.sub(r"\b\d{3,4}p\b", " ", text)          # 1080p, 720p
    text = re.sub(r"\b\d+k\b", " ", text)              # 4k
    text = re.sub(r"\b\d+(\.\d+){1,3}\b", " ", text)   # version-like 2.6.18-4.4.3 parts (broad)

    # 5) remove huge “bends lifespan” numbers etc (10000+)
    text = re.sub(r"\b\d+\+\b", " ", text)

    # 6) keep only letters/numbers/spaces, normalize separators
    text = re.sub(r"[^a-z0-9\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()

    # 7) normalize connector keywords
    tokens = []
    for w in text.split():
        if w in NORMALIZE:
            w = NORMALIZE[w]
        if not w:  # if normalized to ""
            continue

        if w in STOP:
            continue
        if w in NOISE:
            continue
        if w in COLORS:
            continue
        if len(w) <= 2:
            continue

        tokens.append(w)

    return " ".join(tokens)

df["product_name_clean"] = df["product_name"].apply(clean_product_title)

Clean the about_product field value.

In [ ]:
df['about_product'] = df['about_product'].str.lower()

In [ ]:
import re
import pandas as pd
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

STOP = set(ENGLISH_STOP_WORDS)

DOMAIN_NOISE = {
    "compatible", "compatibility", "devices", "device", "enabled", "like", "etc",
    "purchase", "customer", "service", "services", "warranty", "months", "month",
    "date", "contact", "hesitate", "question", "problem", "enjoyment", "ensure",
    "quality", "friendly", "reliable", "respond", "within",
    "offer", "offers", "perfect", "ideal", "best", "comfort", "performance",
    "home", "office",
}

def clean_about_product(text: str) -> str:
    if pd.isna(text):
        return ""

    text = str(text).lower()

    # Replace separators & remove decorative brackets like 【】
    text = text.replace("|", " ")
    text = re.sub(r"[【】\[\]]", " ", text)

    # Remove "compatible with ..." style device lists (biggest noise)
    # This removes phrases that start with "compatible with" up to punctuation/pipe/end.
    text = re.sub(r"compatible with[^.!,;]*", " ", text)

    # Remove explicit apple/android model tokens and common device list words
    text = re.sub(r"\b(iphone|ipad|ipod|ios|android|macbook|chromebook|oneplus|samsung|oppo|vivo|realme|mi)\b", " ", text)
    text = re.sub(r"\b(xr|xs|max|plus|pro|mini|air|se|nano|touch)\b", " ", text)

    # Remove numbers + units/specs (keep the surrounding words like 'fast charging')
    text = re.sub(r"\b\d+(\.\d+)?\s*(mbps|mb/s|gbps|hz|w|a|amp|amps|meter|meters|metre|metres|m|cm|mm|ft|feet|inch|inches|years|year|days|day)\b", " ", text)
    text = re.sub(r"\b\d{3,}\+?\b", " ", text)  # big numbers like 10000+ / 20000

    # Remove punctuation, keep letters/numbers/spaces
    text = re.sub(r"[^a-z0-9\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()

    # Token filter
    tokens = []
    for w in text.split():
        if w in STOP:
            continue
        if w in DOMAIN_NOISE:
            continue
        if len(w) <= 2:
            continue
        tokens.append(w)

    return " ".join(tokens)

In [ ]:
df["about_product_clean"] = df["about_product"].apply(clean_about_product)

In [ ]:
# Install necessary libraries
!pip install -q nltk spacy docx2txt pandas matplotlib wordcloud

# Download NLTK data
import nltk
nltk.download('punkt')        # For tokenization
nltk.download('stopwords')    # For stop words
nltk.download('wordnet')      # For lemmatization
nltk.download('averaged_perceptron_tagger') # For POS tagging
nltk.download('omw-1.4')      # For WordNet data
nltk.download('punkt_tab')    # Download the missing resource for sentence tokenization

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [ ]:
from nltk.tokenize import word_tokenize

def tokenize_words(text_line):
    """Tokenizes words from a list of 100 text samples."""
    tokenized_texts = word_tokenize(text_line)
    return tokenized_texts

tokenized_words = df['about_product_clean'].apply(tokenize_words).apply(pd.Series)
tokenized_words_list = tokenized_words.values.tolist()

In [ ]:
#Let's remove stop words from the cleaned text. The stop words are like is, the, there etc.
#Following code is using the nltk
from nltk.corpus import stopwords

nltk_stop_words = set(stopwords.words('english'))

nltk_tokens_no_stop_words_list = []

for item in tokenized_words_list:
  item_list = []
  for word in item:
    if word not in nltk_stop_words:
      item_list.append(word)
  nltk_tokens_no_stop_words_list += item_list

In [ ]:
#let's remove all the NAN from the token list
nltk_tokens_words_list = []
for item in nltk_tokens_no_stop_words_list:
  if item == item and item != None:
    nltk_tokens_words_list.append(item)

In [ ]:
df['about_product_clean'].head(5)

0                                                                                                                                  high xsmax nano7 apple fast charge data sync charge sync simultaneously rapid speed multi port charging station power bank durability durable nylon braided design premium aluminum housing toughened nylon fiber wound tightly cord lending superior durability adding bit flexibility high security level designed fully protect damaging excessive current copper core multilayer shielding anti interference protective circuit equipment ensures long time meet don
1                                                                                                                                                                                                                                                                                                                               smartphone tablet laptop supports quick charging unbreakable special braided outer rugged interior bindings ultra durable cable won affected daily rough usage length length short typical cable long cable supports maximum fast charging data transfer speed manufacturer
2    fast charger data sync built safety proctections core copper wires promote maximum signal strength enhance charging data transfer speed transferring speed sturdy durable jacket enforced connector tpe premium copper resistant repeatedly bending coiling ultra high according experimental results fishbone design accept bending insertion tests extra protection durability upgraded aluminum connector exclusive laser welding technology metal won break tighter connection fits protective case loose connection good sales hours confidence sale includes day worry free prove importance set
3                                                                                                                                                                boat deuce usb cable tablets peripherals bluetooth speakers power banks type micro usb port ensures fast charging data transmissions rapid sync premium nylon braided skin makes sturdy invincible external damage aluminium alloy shell housing makes longer bends lifespan extended frame protection strain relief resilient flexible design tangle free experience seamlessly deuce usb cable length smooth hassle free user experience
4                                                                                                                                                                                                                                                                                                                                  charge sync function cable comes charging data sync function high material tpe nylon material make sure life cable enhanced significantly long cord cable extra long optimized easy use durable cable unique interms design multi use positioned provide using universal
Name: about_product_clean, dtype: object

In [ ]:
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
import nltk

nltk.download('punkt')
nltk.download('stopwords')


stemmer = PorterStemmer()
stop_words = set(stopwords.words('english'))

def clean_text_stemm(text):
  tokens = word_tokenize(text)
  cleaned = [stemmer.stem(word) for word in tokens if word.lower() not in stop_words]
  # Join back to string
  cleaned_text = " ".join(cleaned)
  return cleaned_text

df['about_product_final'] = df['about_product_clean'].apply(clean_text_stemm).apply(pd.Series)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
df[["about_product", "about_product_final"]].head(2)

,about_product,about_product_final
0,"high compatibility : compatible with iphone 12, 11, x/xsmax/xr ,iphone 8/8 plus,iphone 7/7 plus,iphone 6s/6s plus,iphone 6/6 plus,iphone 5/5s/5c/se,ipad pro,ipad air 1/2,ipad mini 1/2/3,ipod nano7,ipod touch and more apple devices.|fast charge&data sync : it can charge and sync simultaneously at a rapid speed, compatible with any charging adaptor, multi-port charging station or power bank.|durability : durable nylon braided design with premium aluminum housing and toughened nylon fiber wound tightly around the cord lending it superior durability and adding a bit to its flexibility.|high security level : it is designed to fully protect your device from damaging excessive current.copper core thick+multilayer shielding, anti-interference, protective circuit equipment.|warranty: 12 months warranty and friendly customer services, ensures the long-time enjoyment of your purchase. if you meet any question or problem, please don't hesitate to contact us.",high xsmax nano7 appl fast charg data sync charg sync simultan rapid speed multi port charg station power bank durabl durabl nylon braid design premium aluminum hous toughen nylon fiber wound tightli cord lend superior durabl ad bit flexibl high secur level design fulli protect damag excess current copper core multilay shield anti interfer protect circuit equip ensur long time meet
1,"compatible with all type c enabled devices, be it an android smartphone (mi, samsung, oppo, vivo, realme, oneplus, etc), tablet, laptop (macbook, chromebook, etc)|supports quick charging (2.0/3.0)|unbreakable – made of special braided outer with rugged interior bindings, it is ultra-durable cable that won’t be affected by daily rough usage|ideal length – it has ideal length of 1.5 meters which is neither too short like your typical 1meter cable or too long like a 2meters cable|supports maximum 3a fast charging and 480 mbps data transfer speed|6 months manufacturer warranty from the date of purchase",smartphon tablet laptop support quick charg unbreak special braid outer rug interior bind ultra durabl cabl affect daili rough usag length length short typic cabl long cabl support maximum fast charg data transfer speed manufactur

Exploritary data analysis -  
(1) Explore the relation between discount and ratings
(2) Explore the relation between discount rating counts
(3) Explore top category which has highest discount
(4) Explore top category which has highest ratings
(5) Explore category which generates most revenue
(6) Explore products which have the highest ratings

In [ ]:
df['top_category'].unique()

array(['Computers&Accessories', 'Electronics', 'MusicalInstruments',
       'OfficeProducts', 'Home&Kitchen', 'HomeImprovement', 'Toys&Games',
       'Car&Motorbike', 'Health&PersonalCare'], dtype=object)

In [ ]:
df[df['top_category']=='Home&Kitchen'].max().reset_index()

,index,0
0,product_id,B0BR4F878Q
1,product_name,"zuvexa usb rechargeable electric foam maker - handheld milk wand mixer frother for hot milk, hand blender coffee, egg beater (black)"
2,category,Home&Kitchen|Kitchen&HomeAppliances|WaterPurifiers&Accessories|WaterPurifierAccessories
3,discounted_price,999
4,actual_price,9999
5,discount_percentage,90%
6,rating,4.8
7,rating_count,270563.0
8,about_product,"🔥ptc ceramic chip heating technology: the eopora heater is powered by ptc ceramic chip heating technology with 1 second instant heat, which can heat a room faster and quickly and efficiently heating can quickly cover your office or room in minutes.|🔥2 temperature adjustment modes: high heat (1500w) / low heat (1000w).the button on the back can control low temperature/off/high temperature, which is convenient to use.our space heater features 2 different heat settings (low, high).you can switch between different modes more flexibly according to different environments.|🔥tip-over protection & over-heat protection: room heater automatically turn off if they accidentally tip over, perfect for houses with kids and pets. when the heater overheats, the overheat protection will also automatically shut down the heater, making it safer for you to use.|🔥low noise to use: room heaters have noise levels below 50 db. our room heater can provide warmth without interruption for the spaces you need to study, read, work and sleep.|🔥perfect for your home or office: the compact and portable design combined with the ergonomic built-in handle, will allow you to easily move your space heater to any room you want. make sure your office, kitchen, bedroom, guest room, study or living room is nice and warm.|🔥1 year warranty: eopora ptc ceramic fast heating room heater has professional after -sales service and 12 -month warranty. if you have any questions or doubts, please contact us, we will solve your problems as soon as possible."
9,user_id,"AHZJHJWFZLYD64GVP4PXVI2F4LXA,AEUCRZPOISXKHXMCZUH6BXTUXUWA,AFL2ICS3EEESPGYLFF7OTVYMLVJA,AG63J3CFIT6RYX32RHHYWRZ2WKKA,AE6EGCFBVJIZEZ4XPPIY3PES2SDQ,AHUZG5YJCM4UWL66ALQ744FD3OOA,AEIKB2XA64MPG7BBXRG4DT57QKPQ,AF4ECPZRARF7SK2GDSBPTINVA2CA"
10,user_name,"⚡ Pushpendra Singh Patel ⚡,Mukul,Sauron,Amazon Customer,Bumble Bee,Naresh,Serena A Lyngdoh,Sohail Quazi"
11,review_id,"RZXPK0F5S2VTS,RHQXPF9G54YP4,R3MQ0FZCHTDIXT,R2YQQJIT5CF1YI,RQFWTYF7ISOCK,R2WARTYO91TQ5U,R2ZQ5A84YMYF5L,R2EAC2MQLUOE2O"
12,review_title,"💥,Considering the price range, it’s a good one,Worthy,Good products,Good,Good as brand,Ok Product,Value for money,"
13,review_content,"🔸Everything is nice,including design & function,works as intended and mostly as description.🔹But here are things that couldimproved.🔹the upper lid should be able to open up a bit more to the back if we want to wash it more thoroughly since having lid not open in a way that it goes a bit back enough for the lid to not feel a bit in the way its not as comfortable as it could be (this shouldnt become a point which should make ppl avoid buying it though since many other models seem to open up till the same angle as this one does unless you found one that opens up more than this one, if you already bought it or still want to buy it you can use a big bottle brush to scrub it even tho your hand can go in but you ll feel like you have to be more careful while Washing to not accidentally hit the lid (you can see from my image/product image)🔹rest of the body seems sturdy but the handle feels a bit lighter than the body so it makes me wonder if handle would fall off due to daily strain when i pick up the kettle by handle alone (may be it wont break/come off but i hold the kettle with both hands on both ends just in case to be safe) : these are two things i d like to be improved if agaro makes any changes in the model features in future.I didnt return it though because chances are other models are the same or similar and apart from all that it works well.. So yeah.,Very good kettle and big in size,Cord length is good,It is very robust in temperature control. That is to say on and off manual and automatic off. Regarding cord, it is 1500 watts kettle which is on the top of ordinary Indian domestic non power 6A plug. They have given one meter quality wire with 6A plug. This means if your home wiring can stand 1500 watts on ordinary non power plug you can use it in any socket anywhere. (The switch in the kettle is bit wobbly, not sure whether it is purposely designed so: initially I was not pleased, now love it because of majestic performance),Product looks good. Value for money.,seems good until now... hope will last long... good purchase 👌,Kettle is nice 👍 and cord length is also good but package 📦 is not good,at the time of delivery it was opened,"
14,img_link,https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/51zIKeCjN-L._SX300_SY300_QL70_FMwebp_.jpg
15,product_link,https://www.amazon.in/n1-Retail-Stainless-Indian-Coffee/dp/B08KS2KQTK/ref=sr_1_393?qid=1672923612&s=kitchen&sr=1-393
16,top_category,Home&Kitchen
17,product_name_clean,zuvexa usb rechargeable electric foam maker handheld milk wand mixer frother hot milk hand blender coffee egg beater
18,about_product_clean,worry overheating issue room heater presented activa comes heat safety protection prevents damages caused overheating activa room heater features heat settings watts watts right heat intensity suitable size rooms offices places thermal cut added safety protection pure copper wire motor longer life bis approved isi specification throw range room offices product placed vertically horizontally kindly refer images lightweight easy portability rooms plastic body rust free metal grill suits room attire worry experience burning smell run room heater 1st time motor varnish getting heated 1st time recur subsequent usage manufactured guidance highly qualified engineers life product help guidance note product repaired center exclusives comes protection motor
19,about_product_final,worri overh issu room heater present activa come heat safeti protect prevent damag caus overh activa room heater featur heat set watt watt right heat intens suitabl size room offic place thermal cut ad safeti protect pure copper wire motor longer life bi approv isi specif throw rang room offic product place vertic horizont kindli refer imag lightweight easi portabl room plastic bodi rust free metal grill suit room attir worri experi burn smell run room heater 1st time motor varnish get heat 1st time recur subsequ usag manufactur guidanc highli qualifi engin life product help guidanc note product repair center exclus come protect motor

In [ ]:
rating_result = (
    df.groupby('top_category', as_index=False)
      .agg(
          min_rating=('rating', 'min'),
          max_rating=('rating', 'max')
      )
      .sort_values(by='top_category')
)

rating_result

            top_category  min_rating  max_rating
0          Car&Motorbike         3.8         3.8
1  Computers&Accessories         3.0         5.0
2            Electronics         2.8         4.7
3    Health&PersonalCare         4.0         4.0
4           Home&Kitchen         2.0         4.8
5        HomeImprovement         4.0         4.5
6     MusicalInstruments         3.8         4.0
7         OfficeProducts         4.0         4.5
8             Toys&Games         4.3         4.3

In [ ]:
discount_result = (
    df.groupby('top_category', as_index=False)
      .agg(
          min_discount=('discount_percentage', 'min'),
          max_discount=('discount_percentage', 'max')
      )
      .sort_values(by='top_category')
)

discount_result

            top_category min_discount max_discount
0          Car&Motorbike          42%          42%
1  Computers&Accessories           0%          94%
2            Electronics           0%          91%
3    Health&PersonalCare          53%          53%
4           Home&Kitchen           0%          90%
5        HomeImprovement          57%          58%
6     MusicalInstruments          32%          60%
7         OfficeProducts           0%          75%
8             Toys&Games           0%           0%

In [ ]:
actual_price_result = (
    df.groupby('top_category', as_index=False)
      .agg(
          min_actual_price=('actual_price', 'min'),
          max_actual_price=('actual_price', 'max')
      )
      .sort_values(by='top_category')
)

actual_price_result

            top_category min_actual_price max_actual_price
0          Car&Motorbike             4000             4000
1  Computers&Accessories             1000              999
2            Electronics             1000             9999
3    Health&PersonalCare             1900             1900
4           Home&Kitchen              100             9999
5        HomeImprovement              599              999
6     MusicalInstruments             1995              699
7         OfficeProducts              100               99
8             Toys&Games              150              150

In [ ]:
rating_count_result = (
    df.groupby('top_category', as_index=False)
      .agg(
          min_rating_count=('rating_count', 'min'),
          max_rating_count=('rating_count', 'max')
      )
      .sort_values(by='top_category')
)

rating_count_result

            top_category  min_rating_count  max_rating_count
0          Car&Motorbike            1118.0            1118.0
1  Computers&Accessories               5.0          253105.0
2            Electronics               7.0          426973.0
3    Health&PersonalCare            3663.0            3663.0
4           Home&Kitchen               2.0          270563.0
5        HomeImprovement            2581.0            5985.0
6     MusicalInstruments           20218.0           68664.0
7         OfficeProducts             388.0           12179.0
8             Toys&Games           15867.0           15867.0

In [ ]:
df['rating_count'] = pd.to_numeric(
    df['rating_count'].astype(str).str.replace(',', '', regex=False),
    errors='coerce'
)

# Clean discounted_price: keep only digits (and decimal if present), convert
df['discounted_price'] = pd.to_numeric(
    df['discounted_price'].astype(str).str.replace(',', '', regex=False),
    errors='coerce'
)

In [ ]:
df['revenue'] = df['discounted_price'] * df['rating_count']

In [ ]:
#Assuming the number of review counts are equal to one purchase. With this assumption following are the top categories which are generating most revenue for business
revenue_by_category = df.groupby('top_category',as_index=False)['revenue'].sum().sort_values('top_category')
revenue_by_category.sort_values('revenue')

            top_category       revenue
8             Toys&Games  2.380050e+06
5        HomeImprovement  2.587190e+06
0          Car&Motorbike  2.615002e+06
3    Health&PersonalCare  3.293037e+06
7         OfficeProducts  4.578673e+07
6     MusicalInstruments  6.445808e+07
1  Computers&Accessories  5.970035e+09
4           Home&Kitchen  6.264336e+09
2            Electronics  5.703892e+10

***Content-Based Recommendation Approach***

In [ ]:
#make a copy of the original dataframe for collaborative filtering approach. In content based filtering I am not cosidering user_id or user_name
df_collaborative = df.copy()
df.drop(columns=['product_id','category','discounted_price','discount_percentage','about_product','user_id','user_name','review_id','review_title','review_content','img_link','product_link','product_name','revenue','about_product_clean'],inplace=True)

In [ ]:
df["content"] = (
    df["product_name_clean"].fillna("") + " " +
    df["about_product_final"].fillna("")
)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    min_df=2,            # ignore very rare words
    ngram_range=(1, 2),  # use unigrams + bigrams
    max_features=50000   # optional cap
)

X = tfidf.fit_transform(df["content"])

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [ ]:
df[df['top_category']=='HomeImprovement'].head(10)

,actual_price,rating,rating_count,top_category,product_name_clean,about_product_final,content
805,999,4.0,2581.0,HomeImprovement,esnipe mart worldwide travel adapter build dual usb charger ports 125v 250v protected electrical plug cameras,slow charg input output tear plastic film surfac use dual usb port dc5v work phone laptop camera indoor use accept plug countri usa china japan plug equip built safeti shutter includ univers adapt instruct english chines cabl includ differ input plug tightli connect adapt equip built safeti shutter charger adapt plug convert power outlet convert electr output current voltag,esnipe mart worldwide travel adapter build dual usb charger ports 125v 250v protected electrical plug cameras slow charg input output tear plastic film surfac use dual usb port dc5v work phone laptop camera indoor use accept plug countri usa china japan plug equip built safeti shutter includ univers adapt instruct english chines cabl includ differ input plug tightli connect adapt equip built safeti shutter charger adapt plug convert power outlet convert electr output current voltag
982,599,4.5,5985.0,HomeImprovement,gizga essentials cable organiser cord management home theater speaker cables reusable cable organizer desk wfh accessories organizer tape roll reusable cable ties strap,gizga essenti reusabl cabl tie usabl lose grip strength hold cabl place fasten doubl side hook loop tape hook loop doubl side allow cut custom length ring wrap unsightli cabl valu combo pack cabl tie come diy extra long tie cut prefer length use adjust size meet differ need strap cut size easili cut size want gizga essenti product come year peac mind failur perform promis,gizga essentials cable organiser cord management home theater speaker cables reusable cable organizer desk wfh accessories organizer tape roll reusable cable ties strap gizga essenti reusabl cabl tie usabl lose grip strength hold cabl place fasten doubl side hook loop tape hook loop doubl side allow cut custom length ring wrap unsightli cabl valu combo pack cabl tie come diy extra long tie cut prefer length use adjust size meet differ need strap cut size easili cut size want gizga essenti product come year peac mind failur perform promis

In [ ]:
def recommend_by_index(idx, top_n=10, same_category=True):
    query_vec = X[idx]
    scores = cosine_similarity(query_vec, X).flatten()

    # exclude itself
    #scores[idx] = -1

    if same_category:
        cat = df.loc[idx, "top_category"]
        mask = (df["top_category"] == cat).to_numpy()
        scores = np.where(mask, scores, -1)

    top_idx = np.argsort(scores)[::-1][:top_n]

    return df.loc[top_idx, ["product_name_clean", "top_category", "rating", "rating_count"]].assign(similarity=scores[top_idx])

In [ ]:
recommend_by_index(300, top_n=5, same_category=True)

,product_name_clean,top_category,rating,rating_count,similarity
300,lava charging adapter elements fast charging speed usb cable,Computers&Accessories,3.7,41.0,1.000000
5,ptron solero tb301 fast charging cable strong durable meter nylon braided usb cable charging adapter,Computers&Accessories,3.9,24871.0,0.597101
398,portronics adapto fast adapter charger fast charging plus galaxy,Electronics,4.1,8599.0,0.597101
497,iqoo vivo snapdragon 778g flashcharge 1300 nits peak brightness hdr10,Electronics,4.3,9499.0,0.595289
35,ptron solero mb301 micro usb charging cable strong durable meter nylon braided usb cable micro usb,Computers&Accessories,3.9,24871.0,0.595289

In [ ]:
def recommend_by_partial_name(query, top_n=10, same_category=True):
    matches = df[df["product_name_clean"].str.lower().str.contains(query.lower(), na=False)]
    if matches.empty:
        return "No match found."
    idx = matches.index[0]
    return recommend_by_index(idx, top_n=top_n, same_category=same_category)

In [ ]:
recommend_by_partial_name("iqoo vivo snapdragon 778g", top_n=5)

,product_name_clean,top_category,rating,rating_count,similarity
450,iqoo vivo snapdragon 778g flashcharge 1300 nits peak brightness hdr10,Electronics,4.3,9499.0,1.000000
507,sandisk ultra microsdxc uhs card 256gb 150mb warranty,Electronics,4.4,67260.0,0.975385
480,tukzer capacitive stylus pen touch screens fine point lightweight metal body magnetism cover cap,Electronics,3.8,16557.0,0.211320
445,samsung galaxy m13 6000mah battery upto 12gb ram ram plus,Electronics,4.1,18998.0,0.211320
495,boat flash edition smart watch activity tracker multiple sports modes screen 170 watch faces sleep monitor gesture camera music control ip68 days battery life,Electronics,4.0,26880.0,0.208175

Collaborative Filtering

In [ ]:
df_collaborative.drop(columns=['discounted_price','discount_percentage','about_product','review_content','product_name','revenue','about_product_clean','img_link','product_link','category','review_id'],inplace=True)

Now let's explode data based on the user_id so that we can perform the collaborative filtering

In [ ]:
# 1. Split user_id into list
df_collaborative["user_id"] = df_collaborative["user_id"].str.split(",")

# 2. Explode into multiple rows
df_collaborative = df_collaborative.explode("user_id")

# 3. Clean whitespace (VERY IMPORTANT)
df_collaborative["user_id"] = df_collaborative["user_id"].str.strip()

# 4. Reset index
df_collaborative.reset_index(drop=True, inplace=True)

In [ ]:
df_collaborative.head(2)

,product_id,actual_price,rating,rating_count,user_id,user_name,review_title,top_category,product_name_clean,about_product_final
0,B07JW9H4J1,1099,4.2,24269.0,AG3D6O4STAQKAY2UVGEUV46KN35Q,"Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jaspreet singh,Khaja moin,Anand,S.ARUMUGAM","Satisfied,Charging is really fast,Value for money,Product review,Good quality,Good product,Good Product,As of now seems good",Computers&Accessories,wayona nylon braided usb lightning fast charging cable,high xsmax nano7 appl fast charg data sync charg sync simultan rapid speed multi port charg station power bank durabl durabl nylon braid design premium aluminum hous toughen nylon fiber wound tightli cord lend superior durabl ad bit flexibl high secur level design fulli protect damag excess current copper core multilay shield anti interfer protect circuit equip ensur long time meet
1,B07JW9H4J1,1099,4.2,24269.0,AHMY5CWJMMK5BJRBBSNLYT3ONILA,"Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jaspreet singh,Khaja moin,Anand,S.ARUMUGAM","Satisfied,Charging is really fast,Value for money,Product review,Good quality,Good product,Good Product,As of now seems good",Computers&Accessories,wayona nylon braided usb lightning fast charging cable,high xsmax nano7 appl fast charg data sync charg sync simultan rapid speed multi port charg station power bank durabl durabl nylon braid design premium aluminum hous toughen nylon fiber wound tightli cord lend superior durabl ad bit flexibl high secur level design fulli protect damag excess current copper core multilay shield anti interfer protect circuit equip ensur long time meet

In [ ]:
df_collaborative.drop(columns=['user_name'],inplace=True)

In [ ]:
# Start from your 3-column dataframe
df_user_based = df_collaborative[["user_id", "product_id", "rating"]].copy()

# 1️⃣ Split the comma-separated product_id strings into lists
df_user_based["product_id"] = df_user_based["product_id"].astype(str).str.split(",")

# 2️⃣ Explode the lists into separate rows
df_user_exploded = df_user_based.explode("product_id")

# 3️⃣ Optional: strip spaces around product IDs
df_user_exploded["product_id"] = df_user_exploded["product_id"].str.strip()

In [ ]:
#Split the user based dataset into train and test dataset
from sklearn.model_selection import train_test_split

# df is your original DataFrame
train_df_user_based, test_df_user_based = train_test_split(
    df_user_exploded,
    test_size=0.2,      # 40% test, 60% train
    random_state=42,    # for reproducible split
    shuffle=True        # shuffle before splitting (default True)
)

In [ ]:
train_df_user_based.shape

(8542, 3)

In [ ]:
test_df_user_based.shape

(2136, 3)

In [ ]:
!pip install -q lightfm

In [ ]:
from lightfm import LightFM
from lightfm.data import Dataset
import numpy as np

In [ ]:
# Step 2.1: Initialize Dataset
dataset = Dataset()
dataset.fit(
    users=train_df_user_based['user_id'].unique(),
    items=train_df_user_based['product_id'].unique()
)

# Step 2.2: Build interactions with float ratings
interactions, weights = dataset.build_interactions(
    [(row['user_id'], row['product_id'], float(row['rating']))
     for _, row in train_df_user_based.iterrows()]
)

print("Unique interaction weights:", np.unique(weights.tocoo().data))

Unique interaction weights: [2.  2.3 2.6 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9 4.  4.1 4.2
 4.3 4.4 4.5 4.6 4.7 4.8 5. ]

In [ ]:
train_df_user_based

                           user_id  product_id  rating
1034  AFL6MZDS6GWY7546AYCY3Q5L636A  B01D5H8LDM     4.4
5491  AFZOAPDLJIFD3YE3HDLTHDSWUXNA  B08QDPB1SL     4.4
4181  AFF3B5BNL52NXU2E3X5MOBNVGKGA  B0B2X35B1K     4.1
3387  AHN5GP2G4PSPXMVTCK3D7FJSUMFQ  B09MZCQYHZ     4.0
906   AELSOXQRZBOFSSY4HJUR4Y7ASQBA  B09RX1FK54     4.1
...                            ...         ...     ...
5734  AHBXADPUQXAIJI5XTHUKDWD3OQLA  B07Z1YVP72     4.3
5191  AGJ7FX6Z4B7QEM6DG2BT26XG6XWA  B01N6LU1VF     4.3
5390  AFF5WUW7WRVIFAPDQNHER4FCQFAA  B0972BQ2RS     4.1
860   AGOKXS4TP2M6LTNG5HAEMLCKI2IA  B0981XSZJ7     4.3
7270  AH2OOR5NWZ5OB4GTDQ24D6CS6DNQ  B07VNFP3C2     3.9

[8542 rows x 3 columns]

In [ ]:
from scipy.sparse import coo_matrix

# Convert to COO if not already
interactions = interactions.tocoo()
weights = weights.tocoo()
import pandas as pd

interactions_df = pd.DataFrame({
    'user_id': interactions.row,
    'product_id': interactions.col,
    'interaction': interactions.data
})

weights_df = pd.DataFrame({
    'user_id': weights.row,
    'product_id': weights.col,
    'weight': weights.data
})

In [ ]:
from lightfm import LightFM
# STEP 3: Train the LightFM model using WARP loss
model = LightFM(no_components=32, loss='warp', random_state=42)

# Train using both interactions and weights
model.fit(interactions, sample_weight=weights, epochs=20, num_threads=2)
print("Model trained!")

Model trained!

In [ ]:
def recommend_products_for_user(model, dataset, user_id, product_df, N=5):
    # Extract LightFM internal mappings
    user_id_map, _, item_id_map, _ = dataset.mapping()

    # Check if user_id exists in mapping
    if user_id not in user_id_map:
        raise ValueError(f"User ID {user_id} not found in the dataset mapping.")

    internal_user_id = user_id_map[user_id]
    num_items = len(item_id_map)

    # Predict scores for all items for the user
    scores = model.predict(user_ids=internal_user_id, item_ids=np.arange(num_items))

    # Get top N item indices (internal IDs)
    top_indices = np.argsort(-scores)[:N]  # negative for descending sort

    # Reverse mapping: internal → external movie_id
    inv_item_id_map = {v: k for k, v in item_id_map.items()}
    recommended_product_ids = [inv_item_id_map[i] for i in top_indices]

    # Get movie titles
    recommended_products = product_df[product_df['product_id'].isin(recommended_product_ids)]
    recommended_products = recommended_products.set_index('product_id').loc[recommended_product_ids].reset_index()

    return recommended_products

In [ ]:
user_id_to_predict = 'AH2OOR5NWZ5OB4GTDQ24D6CS6DNQ'  # External user_id (e.g., from dataset)
top_recommendations = recommend_products_for_user(model, dataset, user_id=user_id_to_predict, product_df=df_collaborative, N=5)

print(f"Top 5 recommended movies for User {user_id_to_predict}:")
df_unique_top_recommendations = top_recommendations.drop_duplicates(subset="product_id", keep="first")

df_unique_top_recommendations

Top 5 recommended movies for User AH2OOR5NWZ5OB4GTDQ24D6CS6DNQ:

,product_id,actual_price,rating,rating_count,user_id,review_title,top_category,product_name_clean,about_product_final
0,B07VNFP3C2,1245,3.9,31783.0,AEDCFJT7COKZ3DP4YGWKH6KU7LAA,"Good Product Worst Delivery,Overall is ok but outer steel kafi hot 🔥 ho jata he,jo kids k liye kafi harmful he,Nice product,Lovely Product, but filtering holes are big for Ants to get in,Don't buy prestige water kettle product,best product,Medium,Heats up on handle and sides.",Home&Kitchen,prestige litre kettle 1500 watts,provid manufactur differenti great featur automat cutoff degre swivel base iii singl lid lock lockabl lid ye power watt voltag capac liter power watt wash base kettl queri care day 8am 8pm kettl maximum limit mention insid kettl overfil time boil water lid heat plastic smell come overfil leakag happen
8,B09MKP344P,12999,4.1,6662.0,AFBPBZLHAOY5FLNKXSMY7R5NGW4A,"I have been using this phone since 2month it's very good on problem,Nice products,nice product,I am giving 9 out of 10.,Ek dam mst,Tecno Spark 8T,Gud,Lag",Electronics,tecno spark 50mp camera 7gb expandable ram,50mp high resolut camera extra clariti larg apertur 8mp cam dual flash support africa frequenc band fhd segment lead display screen bodi ratio new metal code design bold appeal youth centric 5000mah power batteri ultra power save mode helio g35 game processor robust usag
16,B08MVXPTDG,4200,4.1,63.0,AGYS2OMZE7DCEFQOBUJ7OSMPG3DQ,"no,Good and reliable product 👍,Overall very fine Quality,Useful product helped my family a lot in winter,Operating switch is too hard for aged person,Sabse badhiya,Good product,Good product at this price",Home&Kitchen,crompton insta delight fan circulator room heater heat settings,tap natur phenomenon known convect instadelight circul fan pass heat element easi portabl multipl heat set make quintessenti applianc chilli day come heat set turbo fan design spread heat quickli room power heat protect height adjust stand eas use isi approv product power shock proof bodi carri handl provid crompton cover manufactur defect kindli read usermanu detail
24,B01L6MT7E0,11995,4.1,4157.0,AHLGRFI7QX34GNBZPPXAU3XDMUEA,"Good Performing Air Purifier at a Decent Price,Value for money,Nothing earth shaking about this product!,It is good,Great product.,The product is working nicely and worth buying product.,Writing after 1.5 years pros cons solution and trics do read my reviews and vote,Works but no use",Home&Kitchen,philips ac1215 purifier removes airborne pollutants stage filtration true hepa filter,philip brand purifi india sourc euromonitor intern limit consum applianc 2020ed vitashield intellig purif automat sens remov airborn pollut small micron time smaller fast purif purifi standard room minut cadr hour standard room size ceil height recommend room area stage filtrat purifi process pre filter activ carbon filter true hepa filter real time feedback provid feedback color indic airmid certif remov bacteria virus test remov airborn h1n1 viru ecarf certif remov pollen hous dust mite allergi test ecarf auto ambient light adjust light level accord light room night mode
32,B07ZJND9B9,1990,3.9,5911.0,AFCLVEPUPFSZU5KJMDBYKGARGQBQ,"Decently priced fan,Power saving fan low super qwality,Nice one, go for it,Fan rod was missing,Overall good fan at this price,Good,Love it .. nice product,Okay",Home&Kitchen,activa high speed 390 rpm bee approved star rated apsra ceiling fan brown years warranty,box contain fan motor blade set canopi set downroad shackl manufactur guidanc highli qualifi engin life product help guidanc note self instal product repair center materi type aluminium control type button control mount type downrod mount finish type paint

In [ ]:
def get_user_history(user_id, ratings_df, product_df, min_rating=3):
    """Get all movies a user has rated >= min_rating"""
    user_history = ratings_df[(ratings_df['user_id'] == user_id) & (ratings_df['rating'] >= min_rating)]
    return pd.merge(user_history, product_df, on='product_id')

# Step 1: What has user 3 rated highly in training data?
user_history = get_user_history("AFZEG6L4GPWPLCNRA727ERKMBPBA", train_df_user_based, df_collaborative)
user_history=user_history.drop_duplicates(subset="product_id", keep="first")
print(f"\nUser 3 Highly Rated Products:\n{user_history[['product_id']]}")


# Step 2: What did we recommend to user 3?
recommended_3 = recommend_products_for_user(model, dataset, user_id='AFZEG6L4GPWPLCNRA727ERKMBPBA', product_df=df_collaborative, N=5)
df_unique_top_recommendations = recommended_3.drop_duplicates(subset="product_id", keep="first")
print(f"\nTop 5 Recommended Products for User :\n{df_unique_top_recommendations[['product_id']]}")

User 3 Highly Rated Products:
   product_id
0  B07VTFN6HM
8  B08C4Z69LN

Top 5 Recommended Products for User :
    product_id
0   B07VTFN6HM
8   B08C4Z69LN
16  B09N6TTHT6
24  B08D6RCM3Q
32  B07JPX9CR7

Item based reccomondations

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# Item embedding matrix (num_items x embedding_dim)
item_embeddings = model.item_embeddings
#model.item_embeddings is a matrix where each row corresponds to the embedding vector of an item (movie) learned by LightFM during training.

cos_sim_matrix = cosine_similarity(item_embeddings)
item_id_map = dataset.mapping()[2]  # product_id to LightFM index
reverse_item_map = {v: k for k, v in item_id_map.items()}  # index to product_id
def get_top_k_similar_items(product_id, k=5):
    if product_id not in item_id_map:
        print(f"Product ID {product_id} not found in item_id_map.")
        return []

    idx = item_id_map[product_id]
    sim_scores = cos_sim_matrix[idx]

    # Exclude the item itself and get top-k indices
    similar_idx = np.argsort(-sim_scores)  # descending
    similar_idx = similar_idx[similar_idx != idx][:k]  # remove self

    similar_product_ids = [reverse_item_map[i] for i in similar_idx]
    similar_scores = [sim_scores[i] for i in similar_idx]

    return list(zip(similar_product_ids, similar_scores))

In [ ]:
print("Top 3 similar to movie 583:")
print(get_top_k_similar_items('B08CYNJ5KY', k=3))

Top 3 similar to movie 583:
[('B08Y7MXFMK', np.float32(0.5100746)), ('B0763K5HLQ', np.float32(0.4798458)), ('B00GGGOYEU', np.float32(0.47735423))]

Popularity Based Model

In [ ]:
import pandas as pd

# Assuming ratings_train is your DataFrame with columns: user_id, movie_id, rating

# Step 1: Compute average rating and number of ratings per movie
product_stats = df_collaborative.groupby('product_id').agg(
    avg_rating=('rating', 'mean'),
    rating_count=('rating_count','sum')
).reset_index()

# Step 2: Filter movies with a minimum number of ratings to ensure popularity is meaningful
min_ratings = 16000
popular_products = product_stats[product_stats['rating_count'] >= min_ratings]

# Step 3: Sort by average rating and then by number of ratings (descending)
popular_products = popular_products.sort_values(['avg_rating', 'rating_count'], ascending=False)

# Step 4: Recommend top N popular movies
def recommend_popular_products(n=10):
    top_products = popular_products.head(n)
    return top_products[['product_id', 'avg_rating', 'rating_count']]

# Example usage:
top_10_popular = recommend_popular_products(10)
print(top_10_popular)

      product_id  avg_rating  rating_count
1350  B0BR4F878Q         4.8      161409.0
1205  B0B53DS4TF         4.8       31712.0
1145  B0B23LW7NV         4.7       62232.0
1078  B09WN3SRC7         4.7       47480.0
1321  B0BM9H2NY9         4.7       18400.0
1343  B0BP89YBC1         4.7       18137.0
182   B01J1CFO5I         4.6      267472.0
816   B095RTJH1M         4.6      212824.0
205   B01MQ2A86A         4.6       99000.0
90    B00NFD0ETQ         4.6       86080.0

In [ ]:
product_stats.sort_values('rating_count',ascending=False)

      product_id  avg_rating  rating_count
137   B014I8SSD0         4.4     3415784.0
138   B014I8SX4Y         4.4     3415784.0
356   B07KSMBL2H         4.4     3415784.0
317   B07GPXXNNG         4.1     2909704.0
318   B07GQD4K6L         4.1     2909704.0
...          ...         ...           ...
1317  B0BL3R4RGS         3.6           8.0
1347  B0BPJBTB3F         2.0           4.0
1171  B0B3JSWG81         3.1           2.0
1257  B0B94JPY2N         3.0           0.0
1349  B0BQRJ3C47         5.0           0.0

[1351 rows x 3 columns]

In [ ]:
top_10_popular = top_10_popular.merge(df_collaborative[['product_id']], on='product_id', how='left')
top_10_popular = top_10_popular.drop_duplicates(subset="product_id", keep="first")
top_10_popular

    product_id  avg_rating  rating_count
0   B0BR4F878Q         4.8      161409.0
3   B0B53DS4TF         4.8       31712.0
11  B0B23LW7NV         4.7       62232.0
19  B09WN3SRC7         4.7       47480.0
27  B0BM9H2NY9         4.7       18400.0
35  B0BP89YBC1         4.7       18137.0
42  B01J1CFO5I         4.6      267472.0
50  B095RTJH1M         4.6      212824.0
58  B01MQ2A86A         4.6       99000.0
66  B00NFD0ETQ         4.6       86080.0

Hybrid Model

In [ ]:
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

# user-product rating matrix
R = df_collaborative.pivot_table(
    index="user_id",
    columns="product_id",
    values="rating",
    aggfunc="mean",
    fill_value=0
)

# user-user similarity
U_sim = cosine_similarity(R)
U_sim = pd.DataFrame(U_sim, index=R.index, columns=R.index)

def cf_scores_for_user(user_id, k=20):
    """Return CF predicted scores for all products for a given user."""
    if user_id not in R.index:
        raise ValueError("user_id not found")

    sims = U_sim[user_id].drop(user_id).sort_values(ascending=False).head(k)
    neighbor_ids = sims.index
    weights = sims.values

    # weighted sum of neighbors' ratings
    neighbor_ratings = R.loc[neighbor_ids]                 # k x num_products
    pred = np.dot(weights, neighbor_ratings.values) / (weights.sum() + 1e-9)

    return pd.Series(pred, index=R.columns, name="CF_score")

In [ ]:
df_collaborative["content"] = df_collaborative["product_name_clean"].fillna("") + " " + df_collaborative["about_product_final"].fillna("")

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# One row per product for content model
prod_text = df_collaborative.drop_duplicates("product_id")[["product_id", "content"]].set_index("product_id")

tfidf = TfidfVectorizer(min_df=2, ngram_range=(1,2))
X = tfidf.fit_transform(prod_text["content"])  # products x features

# Map product_id -> row index in X
prod_index = pd.Index(prod_text.index)
prod_to_row = {pid:i for i, pid in enumerate(prod_index)}

from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

def content_scores_for_user(user_id, top_m=10):
    user_hist = df_collaborative[df_collaborative["user_id"] == user_id][["product_id","rating"]]
    if user_hist.empty:
        raise ValueError("No history for this user")

    user_hist = user_hist.sort_values("rating", ascending=False).head(top_m)

    rows = [prod_to_row[p] for p in user_hist["product_id"] if p in prod_to_row]
    if not rows:
        raise ValueError("User history products not found in content index")

    # ✅ convert mean vector to normal ndarray
    user_vec = np.asarray(X[rows].mean(axis=0))

    sims = cosine_similarity(user_vec, X).flatten()
    return pd.Series(sims, index=prod_index, name="Content_score")

In [ ]:
def minmax(s):
    s = s.astype(float)
    return (s - s.min()) / (s.max() - s.min() + 1e-9)

def hybrid_recommend(user_id, n=10, alpha=0.6, k=20, top_m=10, min_ratings=16000):
    cf = cf_scores_for_user(user_id, k=k)
    content = content_scores_for_user(user_id, top_m=top_m)

    # align indexes (products)
    scores = pd.concat([cf, content], axis=1).fillna(0)

    # normalize both to 0..1
    scores["CF_norm"] = minmax(scores["CF_score"])
    scores["Content_norm"] = minmax(scores["Content_score"])

    # score fusion
    scores["Fusion"] = alpha * scores["CF_norm"] + (1 - alpha) * scores["Content_norm"]

    # remove already-rated products
    seen = set(df_collaborative.loc[df_collaborative["user_id"] == user_id, "product_id"])
    scores = scores.drop(index=[p for p in seen if p in scores.index], errors="ignore")

    # popularity filter (optional — your existing idea)
    pop_ok = popular_products.set_index("product_id")  # from your code
    scores = scores.join(pop_ok[["avg_rating", "rating_count"]], how="left")
    scores = scores[scores["rating_count"].fillna(0) >= min_ratings]

    return scores.sort_values("Fusion", ascending=False).head(n).reset_index().rename(columns={"index":"product_id"})

In [ ]:
hybrid_recommend("AFZEG6L4GPWPLCNRA727ERKMBPBA", n=10, alpha=0.6)

,product_id,CF_score,Content_score,CF_norm,Content_norm,Fusion,avg_rating,rating_count
0,B06XDKWLJH,0.000000,0.294782,0.0000,0.412515,0.165006,4.4,200048.0
1,B094QZLJQ6,0.000000,0.285535,0.0000,0.399574,0.159830,4.5,402184.0
2,B08ZJDWTJ1,0.000000,0.211167,0.0000,0.295504,0.118202,4.5,406480.0
3,B09TMZ1MF8,0.000000,0.201154,0.0000,0.281492,0.112597,4.4,24232.0
4,B07G3YNLJB,0.000000,0.195284,0.0000,0.273279,0.109311,4.5,743400.0
5,B08GTYFC37,0.000000,0.172678,0.0000,0.241644,0.096658,4.4,331184.0
6,B07JJFSG2B,0.000000,0.152882,0.0000,0.213942,0.085577,4.3,445976.0
7,B01N6LU1VF,0.133781,0.069403,0.0564,0.097122,0.072688,4.3,1512832.0
8,B00NNQMYNE,0.000000,0.120284,0.0000,0.168325,0.067330,4.5,168080.0
9,B07SLMR1K6,0.000000,0.113782,0.0000,0.159225,0.063690,4.3,240464.0

Section F: Bonus: Business Strategy & Deployment

Which model works best for new users ?
Popularity based model will work best for new users. This is conidering the fact user has not purchased any product yet and we did not have history.

Which model works best for returning users ?
Hybrid model will work best because it considers best of the both worlds from content and collaboration perspective.

How can we recommend products with no ratings ?
We can use product based reccomondations.

How would you deploy this system in production?Mention tools/technologies.

What KPIs should Amazon track to measure success?
(1) Amazon should track how many clicks on reccomonded product
(2) Amazon should also click the region where the click originated
(3) Amazon should track how many clicks on reccomondaded products lead to purchase
(4) Amazon should track information like product_id, product_name of reccomonded product which was clicked
(5) Amazon should also track frequency of product being shown on reccomondations