<a href="https://colab.research.google.com/github/atul2017/Machine-Learning-Business-Cases/blob/main/ap_Book_Price_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_excel('Data_Train.xlsx')

In [ ]:
df.describe()

              Price
count   6237.000000
mean     560.707516
std      690.110657
min       25.000000
25%      249.180000
50%      373.000000
75%      599.000000
max    14100.000000

In [ ]:
df.head()

,Title,Author,Edition,Reviews,Ratings,Synopsis,Genre,BookCategory,Price
0,The Prisoner's Gold (The Hunters 3),Chris Kuzneski,"Paperback,– 10 Mar 2016",4.0 out of 5 stars,8 customer reviews,THE HUNTERS return in their third brilliant no...,Action & Adventure (Books),Action & Adventure,220.00
1,Guru Dutt: A Tragedy in Three Acts,Arun Khopkar,"Paperback,– 7 Nov 2012",3.9 out of 5 stars,14 customer reviews,A layered portrait of a troubled genius for wh...,Cinema & Broadcast (Books),"Biographies, Diaries & True Accounts",202.93
2,Leviathan (Penguin Classics),Thomas Hobbes,"Paperback,– 25 Feb 1982",4.8 out of 5 stars,6 customer reviews,"""During the time men live without a common Pow...",International Relations,Humour,299.00
3,A Pocket Full of Rye (Miss Marple),Agatha Christie,"Paperback,– 5 Oct 2017",4.1 out of 5 stars,13 customer reviews,A handful of grain is found in the pocket of a...,Contemporary Fiction (Books),"Crime, Thriller & Mystery",180.00
4,LIFE 70 Years of Extraordinary Photography,Editors of Life,"Hardcover,– 10 Oct 2006",5.0 out of 5 stars,1 customer review,"For seven decades, ""Life"" has been thrilling t...",Photography Textbooks,"Arts, Film & Photography",965.62

In [ ]:
df['Ratings']

0        8 customer reviews
1       14 customer reviews
2        6 customer reviews
3       13 customer reviews
4         1 customer review
               ...
6232     2 customer reviews
6233     9 customer reviews
6234     3 customer reviews
6235     4 customer reviews
6236     2 customer reviews
Name: Ratings, Length: 6237, dtype: object

In [ ]:
df['Ratings'].isnull().sum()

np.int64(0)

In [ ]:
df['Price'].isnull().sum()

np.int64(0)

In [ ]:
df.count()

Title           6237
Author          6237
Edition         6237
Reviews         6237
Ratings         6237
Synopsis        6237
Genre           6237
BookCategory    6237
Price           6237
dtype: int64

In [ ]:
df['Ratings'] = df['Ratings'].str.split().str[0]
df['Ratings']

0        8
1       14
2        6
3       13
4        1
        ..
6232     2
6233     9
6234     3
6235     4
6236     2
Name: Ratings, Length: 6237, dtype: object

In [ ]:
df.head()

,Title,Author,Edition,Reviews,Ratings,Synopsis,Genre,BookCategory,Price
0,The Prisoner's Gold (The Hunters 3),Chris Kuzneski,"Paperback,– 10 Mar 2016",4.0 out of 5 stars,8,THE HUNTERS return in their third brilliant no...,Action & Adventure (Books),Action & Adventure,220.00
1,Guru Dutt: A Tragedy in Three Acts,Arun Khopkar,"Paperback,– 7 Nov 2012",3.9 out of 5 stars,14,A layered portrait of a troubled genius for wh...,Cinema & Broadcast (Books),"Biographies, Diaries & True Accounts",202.93
2,Leviathan (Penguin Classics),Thomas Hobbes,"Paperback,– 25 Feb 1982",4.8 out of 5 stars,6,"""During the time men live without a common Pow...",International Relations,Humour,299.00
3,A Pocket Full of Rye (Miss Marple),Agatha Christie,"Paperback,– 5 Oct 2017",4.1 out of 5 stars,13,A handful of grain is found in the pocket of a...,Contemporary Fiction (Books),"Crime, Thriller & Mystery",180.00
4,LIFE 70 Years of Extraordinary Photography,Editors of Life,"Hardcover,– 10 Oct 2006",5.0 out of 5 stars,1,"For seven decades, ""Life"" has been thrilling t...",Photography Textbooks,"Arts, Film & Photography",965.62

In [ ]:
df['Reviews'] = df['Reviews'].str.split().str[0]
df['Reviews']

0       4.0
1       3.9
2       4.8
3       4.1
4       5.0
       ...
6232    5.0
6233    3.3
6234    3.8
6235    3.5
6236    3.9
Name: Reviews, Length: 6237, dtype: object

In [ ]:
df.head()

,Title,Author,Edition,Reviews,Ratings,Synopsis,Genre,BookCategory,Price
0,The Prisoner's Gold (The Hunters 3),Chris Kuzneski,"Paperback,– 10 Mar 2016",4.0,8,THE HUNTERS return in their third brilliant no...,Action & Adventure (Books),Action & Adventure,220.00
1,Guru Dutt: A Tragedy in Three Acts,Arun Khopkar,"Paperback,– 7 Nov 2012",3.9,14,A layered portrait of a troubled genius for wh...,Cinema & Broadcast (Books),"Biographies, Diaries & True Accounts",202.93
2,Leviathan (Penguin Classics),Thomas Hobbes,"Paperback,– 25 Feb 1982",4.8,6,"""During the time men live without a common Pow...",International Relations,Humour,299.00
3,A Pocket Full of Rye (Miss Marple),Agatha Christie,"Paperback,– 5 Oct 2017",4.1,13,A handful of grain is found in the pocket of a...,Contemporary Fiction (Books),"Crime, Thriller & Mystery",180.00
4,LIFE 70 Years of Extraordinary Photography,Editors of Life,"Hardcover,– 10 Oct 2006",5.0,1,"For seven decades, ""Life"" has been thrilling t...",Photography Textbooks,"Arts, Film & Photography",965.62

In [ ]:
df['Genre'].unique()

array(['Action & Adventure (Books)', 'Cinema & Broadcast (Books)',
       'International Relations', 'Contemporary Fiction (Books)',
       'Photography Textbooks', 'Healthy Living & Wellness (Books)',
       'Crime, Thriller & Mystery (Books)',
       'Sports Training & Coaching (Books)',
       'Biographies & Autobiographies (Books)', 'Asian History',
       'Banks & Banking', 'Comics & Mangas (Books)',
       "Children's Mysteries & Curiosities (Books)", 'Mangas',
       'Artificial Intelligence',
       'Software & Business Applications (Books)', 'German',
       'International Business', 'Cricket (Books)',
       'Comics & Graphic Novels (Books)', 'PC & Video Games (Books)',
       'Short Stories (Books)', 'Astrology', 'Romance (Books)', 'Design',
       'Introductory & Beginning Programming', 'Travel (Books)',
       'Sports (Books)', 'Communications', 'Foreign Languages',
       'Linguistics (Books)', 'Music Books',
       'Outdoor Survival Skills (Books)', 'True Accounts (Books)',
       'Literature', 'Society & Culture (Books)',
       'Industries & Business Sectors (Books)',
       'Programming Languages (Books)', 'Media Studies',
       'Indian Writing (Books)',
       'Networks & System Administration (Books)',
       'Classic Fiction (Books)', 'Dictionaries',
       'Computer Hardware & Handheld Devices (Books)',
       'Government (Books)', 'Arts History, Theory & Criticism (Books)',
       'Science & Mathematics', 'Hunting (Books)',
       'Handicrafts, Decorative Arts & Crafts (Books)', 'Inflation',
       'Religious & Spiritual Fiction (Books)', 'Law (Books)',
       'Vocabulary Books', 'Encyclopaedias & Reference Works (Books)',
       'IT Certification Exams', 'Sign Language Reference',
       'Engineering & Technology (Books)', 'Business Communication',
       'IELTS', "Children's Adventure (Books)", 'Hinduism (Books)',
       "Children's Games, Toys & Activities (Books)",
       'Political Theory (Books)', 'Investments & Securities',
       "Children's Historical Fiction (Books)", 'Sustainable Development',
       'Painting Textbooks', 'Economic Theory', 'Writing Guides (Books)',
       'Budget Travel', 'Biotechnology Engineering Textbooks', 'Sales',
       'Computing, Internet & Digital Media (Books)',
       'Illustrated Travel Books (Books)', 'Comics',
       'Agriculture & Farming (Books)',
       "Children's Crafts, Hobbies & Practical Interests (Books)",
       'Historical Fiction (Books)',
       'Language, Linguistics & Writing (Books)', 'GRE', 'Reincarnation',
       'Public Policy', "Children's Reference (Books)",
       'Film & Television', 'Anthologies (Books)',
       'Personal Development & Self-Help (Books)', 'Martial Arts (Books)',
       'Language & Linguistics',
       'World African & Middle Eastern Literature', 'Soccer (Books)',
       'Grammar (Books)', 'Asian Literature', 'Essays (Books)', 'TOEFL',
       'American Literature', 'GATE Exams',
       'Language Learning & Teaching (Books)',
       'Political Ideologies (Books)', 'Theater',
       'Mind, Body & Spirit (Books)', 'Earth Sciences Textbooks',
       'Climbing & Mountaineering (Books)', 'Programming Algorithms',
       'Horse Racing (Books)', 'Games & Quizzes (Books)',
       'Family & Relationships (Books)',
       "Children's Crime & Thriller (Books)", 'Economics Books',
       'Theatre & Spectacles (Books)', 'Architecture (Books)',
       'Humour (Books)', "Children's Humour (Books)",
       'Internet & Web (Books)', 'Horror (Books)',
       'Fantasy, Science Fiction & Horror (Books)',
       'Programming & Software Development (Books)', 'Algorithms',
       'Entrepreneurship', 'Computer Security (Books)',
       'Food, Drink & Entertaining (Books)', 'Engineering',
       'Anthropology (Books)', 'History (Books)',
       'Computer Science Books', 'IGCSE', 'Visual C++ Programming',
       'Visual Arts', "Children's Fantasy (Books)",
       'Software Architecture', 'Teaching & Education',
       'Public Speaking Reference', 'Public Health', 'Psychology (Books)',
       'United States History', 'Calculus', 'Political Parties (Books)',
       'Zoology', 'Neuroscience', 'Gender Studies', 'General Dentistry',
       'Governmental', 'Economic History',
       'History of Slavery & Emancipation',
       'Economic Policy & Development', 'Astronomy (Books)', 'Ethics',
       'French', 'International Relations & Globalization (Books)',
       'Japanese', 'Software Design & Engineering', 'History & Surveys',
       'Geography Textbooks', 'Crafts, Home & Lifestyle (Books)',
       'Economics Textbooks',
       "Children's Family, Personal & Social Issues (Books)",
       'Computer Databases (Books)', 'Mathematics (Books)',
       'Political Freedom & Security (Books)',
       'Engineering Services Exams',
       'Sporting Events & Organisations (Books)', 'Spirituality',
       "Children's Painting, Arts & Music (Books)",
       "Children's & Young Adult (Books)", 'American Football (Books)',
       'Rhetoric & Speech (Books)', 'Motorcycle Racing', 'Study Guides',
       'Mental & Spiritual Healing', 'Labor & Industrial Relations',
       'Alternative Medicine (Books)', 'FPC', 'Python Programming',
       'Literature & Fiction (Books)', 'Holocaust',
       'Encyclopedias for Children', 'Politics (Books)',
       'Biographies, Diaries & True Accounts (Books)', 'Literary Travel',
       'Triathlon (Books)', 'Travel & Holiday Guides (Books)',
       "Children's Picture Books (Books)", 'Travel with Pets',
       'Reading Skills', 'Baseball (Books)', 'Meditation',
       'Transportation & Automotive (Books)', 'Occupational Therapy',
       'Journalism Books', 'PGMEE Exam', 'History of Religion (Books)',
       'Theory', 'Arts, Film & Photography (Books)',
       'Interface Design Programming',
       'Combat Sports & Self-Defence (Books)',
       'Digital Media & Graphic Design (Books)', 'Food & Lodging',
       'Exam Preparation (Books)', 'Military Sciences',
       'Colonialism & Imperialism History', 'Education & Training',
       'Operating Systems Textbooks', 'Software Testing',
       'Networking (Books)', 'Diaries, Letters & Journals (Books)',
       'Biology Books', 'Government Exams',
       'Society & Social Sciences (Books)', 'Physician & Patient',
       'International Baccalaureate', 'Rugby (Books)',
       'Design & Fashion (Books)', 'Plays (Books)',
       'Aeronautical Engineering', 'Business & Economics (Books)',
       'Literature Encyclopedias', 'Environmental Economics',
       'Intolerance, Persecution & Fundamentalism', 'Islam (Books)',
       'Myths, Legends & Sagas (Books)', 'Golf (Books)',
       'European History', 'Pets (Books)', 'Italian', 'Geometry',
       'Physics (Books)', 'Interview Preparation',
       'Gay & Lesbian Studies', 'Swimming, Snorkelling & Diving (Books)',
       'History of Ideas', 'Religion (Books)',
       'Sciences, Technology & Medicine (Books)', 'Internal Medicine',
       'Pool, Billiards & Snooker (Books)', 'Humanities',
       'Library & Information Science',
       "Children's Traditional Stories (Books)",
       'Business, Strategy & Management (Books)', 'Ecotourism',
       'Anatomy & Physiology', 'Target Shooting (Books)',
       'Political Structure & Processes (Books)',
       'Environmental Engineering', 'Social Sciences',
       'English Literature', 'Microeconomics Textbooks',
       'Social Welfare & Social Services (Books)', 'Alphabet Reference',
       'Business Ethics', 'History of Civilization & Culture',
       'Public Administration (Books)', 'Civil Rights', 'CSS Programming',
       'Management', 'Fishing & Angling (Books)',
       'Algebra & Trigonometry', 'Immunology',
       'Bodybuilding & Weightlifting (Books)', 'Chemistry Books',
       'Music Textbooks', 'Gymnastics (Books)', 'Sociology (Books)',
       'Communication Reference', 'Neurology',
       'XHTML Software Programming', 'Operating Systems Books',
       'International Entrance Exams', 'Sikhism (Books)',
       'Environmental Studies', 'Americas', 'Developmental Psychology',
       'Development & Growth', 'Urban & Regional',
       'Structural Engineering', 'Cold War', 'Painting Books',
       'Graphics & Visualization', 'Marathon & Running (Books)',
       'Walking, Hiking & Trekking (Books)', 'Vascular Surgery',
       'Readers', "Children's Language Learning (Books)", 'Art History',
       "Young Adults' Money & Jobs (Books)", 'Dance (Books)',
       'Car Racing (Books)', 'Design Pattern Programming',
       'Basketball (Books)', 'Buddhism (Books)',
       'Electrical & Electronic Engineering', 'Ancient History (Books)',
       'Astronomy & Astrophysics',
       "Children's Horror & Ghost Stories (Books)",
       'Translation Reference', 'Biomedical Engineering',
       'Sports Medicine', 'SSC Exam', 'Ecology', 'Sailing (Books)',
       'Middle Eastern History',
       "Children's Science, Nature & Technology (Books)",
       'Camping & Woodcraft (Books)', 'Macroeconomics Textbooks',
       'Nuclear Engineering', 'Home & House Maintenance (Books)',
       'Textbooks & Study Guides', 'Public Affairs', 'Archery (Books)',
       'Words, Language & Grammar Reference',
       'Active Outdoor Pursuits (Books)',
       "Children's Science Fiction (Books)", 'European History Textbooks',
       'Art Encyclopedias', 'Flash Cards',
       'Object-Oriented Software Design', 'Waste Management', 'Speech',
       'API & Operating Environments',
       'Radiological & Ultrasound Technology',
       'Software Programming Compilers', 'Biology & Life Sciences',
       'Workbooks', 'Hockey', 'Medicine`', 'History of Ancient Greece',
       'CBSE', 'SAT', "Children's History (Books)", 'Atheism',
       'Industrial Engineering', 'Medical Dictionaries', 'GMAT',
       'Aesthetics', 'Reference (Books)', 'Literary Theory', 'Rome',
       'Essay, Letter & Review Writing', 'Mysticism',
       "Children's Sport (Books)", 'Economic Conditions',
       'C# Programming', 'Game Programming', 'Specialty Travel',
       'Oncology', 'Constitutional Law', 'Air Sports (Books)'],
      dtype=object)

In [ ]:
df['Author'].value_counts()

Author
Agatha Christie                69
Ladybird                       49
DK                             48
Herge                          34
Albert Uderzo                  34
                               ..
Colin Dexter                    1
Arvind Gupta                    1
Ripley's Believe It Or Not!     1
Jonathan Shariat                1
Editors of Life                 1
Name: count, Length: 3679, dtype: int64

In [ ]:
df['Ratings'].sort_values(ascending=False)

3013    99
890     99
5252    99
3827    99
2518    98
        ..
989      1
987      1
477      1
2116     1
4014     1
Name: Ratings, Length: 6237, dtype: object

In [ ]:
df['Price'].sort_values(ascending=False)

2455    14100.00
886     13244.67
2607    11715.12
2818     9984.00
2560     9096.00
          ...
1210       30.00
4000       30.00
2079       28.00
5068       25.00
418        25.00
Name: Price, Length: 6237, dtype: float64

In [ ]:
df['Title_Length'] = df['Title'].str.len()
df['Title_Length']

0       35
1       34
2       28
3       34
4       42
        ..
6232    50
6233    11
6234    54
6235    28
6236    27
Name: Title_Length, Length: 6237, dtype: int64

In [ ]:
df['Edition_Type'] = df['Edition'].str.split().str[0]
df['Edition_Type']

0       Paperback,–
1       Paperback,–
2       Paperback,–
3       Paperback,–
4       Hardcover,–
           ...
6232    Paperback,–
6233    Paperback,–
6234    Paperback,–
6235    Paperback,–
6236    Paperback,–
Name: Edition_Type, Length: 6237, dtype: object

In [ ]:
df.head()

,Title,Author,Edition,Reviews,Ratings,Synopsis,Genre,BookCategory,Price,Title_Length,Edition_Type
0,The Prisoner's Gold (The Hunters 3),Chris Kuzneski,"Paperback,– 10 Mar 2016",4.0,8,THE HUNTERS return in their third brilliant no...,Action & Adventure (Books),Action & Adventure,220.00,35,"Paperback,–"
1,Guru Dutt: A Tragedy in Three Acts,Arun Khopkar,"Paperback,– 7 Nov 2012",3.9,14,A layered portrait of a troubled genius for wh...,Cinema & Broadcast (Books),"Biographies, Diaries & True Accounts",202.93,34,"Paperback,–"
2,Leviathan (Penguin Classics),Thomas Hobbes,"Paperback,– 25 Feb 1982",4.8,6,"""During the time men live without a common Pow...",International Relations,Humour,299.00,28,"Paperback,–"
3,A Pocket Full of Rye (Miss Marple),Agatha Christie,"Paperback,– 5 Oct 2017",4.1,13,A handful of grain is found in the pocket of a...,Contemporary Fiction (Books),"Crime, Thriller & Mystery",180.00,34,"Paperback,–"
4,LIFE 70 Years of Extraordinary Photography,Editors of Life,"Hardcover,– 10 Oct 2006",5.0,1,"For seven decades, ""Life"" has been thrilling t...",Photography Textbooks,"Arts, Film & Photography",965.62,42,"Hardcover,–"

In [ ]:
df['Edition_Type'].unique()

array(['Paperback,–', 'Hardcover,–', 'Mass', 'Sheet', 'Flexibound,–',
       'Plastic', 'Loose', 'Tankobon', 'Perfect', 'Board', 'Cards,–',
       'Spiral-bound,–', '(Kannada),Paperback,–', 'Product', 'Library',
       '(German),Paperback,–', 'Leather', '(French),Paperback,–',
       '(Spanish),Paperback,–'], dtype=object)

In [ ]:
df['Edition_Type'] = df['Edition_Type'].str.replace(",", "").replace("-", "")
df['Edition_Type']

0       Paperback–
1       Paperback–
2       Paperback–
3       Paperback–
4       Hardcover–
           ...
6232    Paperback–
6233    Paperback–
6234    Paperback–
6235    Paperback–
6236    Paperback–
Name: Edition_Type, Length: 6237, dtype: object

In [ ]:
df['Edition_Type'] = df['Edition_Type'].str.replace("-", " ")
df['Edition_Type']

0       Paperback–
1       Paperback–
2       Paperback–
3       Paperback–
4       Hardcover–
           ...
6232    Paperback–
6233    Paperback–
6234    Paperback–
6235    Paperback–
6236    Paperback–
Name: Edition_Type, Length: 6237, dtype: object

In [ ]:
df['Edition_Type'].unique()

array(['Paperback–', 'Hardcover–', 'Mass', 'Sheet', 'Flexibound–',
       'Plastic', 'Loose', 'Tankobon', 'Perfect', 'Board', 'Cards–',
       'Spiral bound–', '(Kannada)Paperback–', 'Product', 'Library',
       '(German)Paperback–', 'Leather', '(French)Paperback–',
       '(Spanish)Paperback–'], dtype=object)

In [ ]:
df.head()

,Title,Author,Edition,Reviews,Ratings,Synopsis,Genre,BookCategory,Price,Title_Length,Edition_Type
0,The Prisoner's Gold (The Hunters 3),Chris Kuzneski,"Paperback,– 10 Mar 2016",4.0,8,THE HUNTERS return in their third brilliant no...,Action & Adventure (Books),Action & Adventure,220.00,35,Paperback–
1,Guru Dutt: A Tragedy in Three Acts,Arun Khopkar,"Paperback,– 7 Nov 2012",3.9,14,A layered portrait of a troubled genius for wh...,Cinema & Broadcast (Books),"Biographies, Diaries & True Accounts",202.93,34,Paperback–
2,Leviathan (Penguin Classics),Thomas Hobbes,"Paperback,– 25 Feb 1982",4.8,6,"""During the time men live without a common Pow...",International Relations,Humour,299.00,28,Paperback–
3,A Pocket Full of Rye (Miss Marple),Agatha Christie,"Paperback,– 5 Oct 2017",4.1,13,A handful of grain is found in the pocket of a...,Contemporary Fiction (Books),"Crime, Thriller & Mystery",180.00,34,Paperback–
4,LIFE 70 Years of Extraordinary Photography,Editors of Life,"Hardcover,– 10 Oct 2006",5.0,1,"For seven decades, ""Life"" has been thrilling t...",Photography Textbooks,"Arts, Film & Photography",965.62,42,Hardcover–

In [ ]:
df['Edition_Type'] = df['Edition_Type'].str.replace(r"[^A-Za-z]","",regex=True)
df['Edition_Type']

0       Paperback
1       Paperback
2       Paperback
3       Paperback
4       Hardcover
          ...
6232    Paperback
6233    Paperback
6234    Paperback
6235    Paperback
6236    Paperback
Name: Edition_Type, Length: 6237, dtype: object

In [ ]:
df.head()

,Title,Author,Edition,Reviews,Ratings,Synopsis,Genre,BookCategory,Price,Title_Length,Edition_Type
0,The Prisoner's Gold (The Hunters 3),Chris Kuzneski,"Paperback,– 10 Mar 2016",4.0,8,THE HUNTERS return in their third brilliant no...,Action & Adventure (Books),Action & Adventure,220.00,35,Paperback
1,Guru Dutt: A Tragedy in Three Acts,Arun Khopkar,"Paperback,– 7 Nov 2012",3.9,14,A layered portrait of a troubled genius for wh...,Cinema & Broadcast (Books),"Biographies, Diaries & True Accounts",202.93,34,Paperback
2,Leviathan (Penguin Classics),Thomas Hobbes,"Paperback,– 25 Feb 1982",4.8,6,"""During the time men live without a common Pow...",International Relations,Humour,299.00,28,Paperback
3,A Pocket Full of Rye (Miss Marple),Agatha Christie,"Paperback,– 5 Oct 2017",4.1,13,A handful of grain is found in the pocket of a...,Contemporary Fiction (Books),"Crime, Thriller & Mystery",180.00,34,Paperback
4,LIFE 70 Years of Extraordinary Photography,Editors of Life,"Hardcover,– 10 Oct 2006",5.0,1,"For seven decades, ""Life"" has been thrilling t...",Photography Textbooks,"Arts, Film & Photography",965.62,42,Hardcover

In [ ]:
df['Ratings'].unique()

array(['8', '14', '6', '13', '1', '72', '16', '111', '132', '17', '4',
       '3', '5', '2', '23', '76', '10', '9', '15', '34', '32', '49', '62',
       '61', '7', '18', '98', '12', '97', '285', '29', '27', '267', '24',
       '146', '95', '234', '35', '66', '20', '39', '171', '399', '42',
       '142', '11', '839', '47', '165', '30', '53', '77', '33', '37',
       '54', '28', '50', '197', '26', '114', '46', '51', '161', '135',
       '41', '156', '1,416', '93', '221', '36', '154', '74', '45', '240',
       '55', '19', '48', '404', '245', '22', '292', '25', '75', '381',
       '44', '443', '425', '21', '238', '84', '68', '108', '52', '57',
       '109', '89', '304', '96', '419', '205', '85', '960', '71', '167',
       '58', '40', '102', '101', '65', '70', '106', '922', '31', '38',
       '63', '177', '138', '164', '257', '207', '64', '56', '196', '82',
       '1,558', '567', '60', '80', '303', '73', '193', '155', '798',
       '128', '87', '90', '286', '565', '137', '99', '403', '277', '902',
       '59', '861', '67', '815', '227', '119', '474', '69', '247', '414',
       '86', '432', '1,142', '168', '382', '79', '141', '220', '732',
       '2,048', '1,097', '226', '649', '160', '140', '2,081', '405',
       '121', '88', '342', '190', '83', '250', '217', '115', '224', '43',
       '136', '230', '283', '184', '186', '110', '187', '81', '107',
       '355', '2,084', '116', '862', '370', '92', '6,090', '215', '893',
       '261', '129', '113', '206', '159', '540', '413', '307', '351',
       '390', '143', '185', '282', '150', '120', '246', '126', '784',
       '174', '397', '172', '158', '863', '291', '225', '1,227', '366',
       '218', '100', '337', '973', '310', '301', '212', '764', '279',
       '255', '251', '653', '894', '3,135', '958', '134', '127', '420',
       '139', '800', '94', '178', '145', '967', '1,392', '264', '122',
       '219', '505', '125', '407', '210', '133', '151', '188', '166',
       '656', '175', '153', '1,684', '149', '163', '199', '157', '203',
       '331', '970', '305', '327', '1,403', '180', '268', '104', '123',
       '290', '396', '287', '244', '670', '223', '117', '867', '91',
       '105', '332', '152', '379', '278', '144', '606', '1,248', '112',
       '295', '450', '298', '899', '570', '871', '356', '249', '179',
       '545', '494', '358', '853', '280', '118', '1,563', '1,259', '200',
       '2,255', '727', '568', '429', '296', '124', '252', '78', '695',
       '3,075', '434', '353', '328', '170', '1,256', '162', '270', '297',
       '615', '421', '253', '325', '308', '804', '551', '288', '483'],
      dtype=object)

In [ ]:
type(df['Ratings'])

pandas.core.series.Series

In [ ]:
#Convert to numeric (optional, if you want it as int)
df['Ratings'] = pd.to_numeric(df['Ratings'], errors='coerce')

In [ ]:
df['Ratings'] = (df['Ratings'] - df['Ratings'].mean()) / df['Ratings'].std()

In [ ]:
df['Ratings']

0      -0.260135
1      -0.188926
2      -0.283871
3      -0.200794
4      -0.343212
          ...
6232   -0.331344
6233   -0.248267
6234   -0.319475
6235   -0.307607
6236   -0.331344
Name: Ratings, Length: 6237, dtype: float64

In [ ]:
df['Reviews'] = pd.to_numeric(df['Reviews'], errors='coerce')

In [ ]:
df['Reviews'] = (df['Reviews'] - df['Reviews'].mean()) / df['Reviews'].std()

In [ ]:
df['Reviews']

0      -0.442568
1      -0.593511
2       0.764977
3      -0.291625
4       1.066863
          ...
6232    1.066863
6233   -1.499169
6234   -0.744454
6235   -1.197283
6236   -0.593511
Name: Reviews, Length: 6237, dtype: float64

In [ ]:
df['Rating_Review_Score'] = df['Ratings'] * df['Reviews']

In [ ]:
df['Rating_Review_Score']

0       0.115127
1       0.112130
2      -0.217155
3       0.058557
4      -0.366160
          ...
6232   -0.353498
6233    0.372194
6234    0.237835
6235    0.368293
6236    0.196656
Name: Rating_Review_Score, Length: 6237, dtype: float64

In [ ]:
!pip install vaderSentiment

Requirement already satisfied: vaderSentiment in /usr/local/lib/python3.12/dist-packages (3.3.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from vaderSentiment) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (2025.11.12)

In [ ]:
import pandas as pd
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [ ]:
analyzer = SentimentIntensityAnalyzer()


def getSentiment(sentence):
  score = analyzer.polarity_scores(sentence)
  return score['compound']

Sentiment_Score = df['Synopsis'].apply(getSentiment)

print("Sentiment_Score->",Sentiment_Score)

def classify_sentiment(score):
  if score >= 0.05:
    return 1
  elif score <= -0.05:
    return -1
  else:
    return 0

df['Synopsis Polatiry'] = Sentiment_Score.apply(classify_sentiment)

Sentiment_Score-> 0       0.8717
1       0.9889
2       0.9791
3      -0.9643
4       0.9080
         ...
6232    0.9575
6233   -0.9097
6234    0.9954
6235    0.9829
6236   -0.9740
Name: Synopsis, Length: 6237, dtype: float64

In [ ]:
df['Synopsis Polatiry']

0       1
1       1
2       1
3      -1
4       1
       ..
6232    1
6233   -1
6234    1
6235    1
6236   -1
Name: Synopsis Polatiry, Length: 6237, dtype: int64

In [ ]:
df.head()

,Title,Author,Edition,Reviews,Ratings,Synopsis,Genre,BookCategory,Price,Title_Length,Edition_Type,Rating_Review_Score,Synopsis Polatiry
0,The Prisoner's Gold (The Hunters 3),Chris Kuzneski,"Paperback,– 10 Mar 2016",-0.442568,-0.260135,THE HUNTERS return in their third brilliant no...,Action & Adventure (Books),Action & Adventure,220.00,35,Paperback,0.115127,1
1,Guru Dutt: A Tragedy in Three Acts,Arun Khopkar,"Paperback,– 7 Nov 2012",-0.593511,-0.188926,A layered portrait of a troubled genius for wh...,Cinema & Broadcast (Books),"Biographies, Diaries & True Accounts",202.93,34,Paperback,0.112130,1
2,Leviathan (Penguin Classics),Thomas Hobbes,"Paperback,– 25 Feb 1982",0.764977,-0.283871,"""During the time men live without a common Pow...",International Relations,Humour,299.00,28,Paperback,-0.217155,1
3,A Pocket Full of Rye (Miss Marple),Agatha Christie,"Paperback,– 5 Oct 2017",-0.291625,-0.200794,A handful of grain is found in the pocket of a...,Contemporary Fiction (Books),"Crime, Thriller & Mystery",180.00,34,Paperback,0.058557,-1
4,LIFE 70 Years of Extraordinary Photography,Editors of Life,"Hardcover,– 10 Oct 2006",1.066863,-0.343212,"For seven decades, ""Life"" has been thrilling t...",Photography Textbooks,"Arts, Film & Photography",965.62,42,Hardcover,-0.366160,1

In [ ]:
df['Author Frequency'] = df['Author'].map(df['Author'].value_counts())
df['Author Frequency']

0        4
1        1
2        3
3       69
4        1
        ..
6232     1
6233     1
6234     3
6235     2
6236     2
Name: Author Frequency, Length: 6237, dtype: int64

In [ ]:
df.head()

,Title,Author,Edition,Reviews,Ratings,Synopsis,Genre,BookCategory,Price,Title_Length,Edition_Type,Rating_Review_Score,Synopsis Polatiry,Author Frequency
0,The Prisoner's Gold (The Hunters 3),Chris Kuzneski,"Paperback,– 10 Mar 2016",-0.442568,-0.260135,THE HUNTERS return in their third brilliant no...,Action & Adventure (Books),Action & Adventure,220.00,35,Paperback,0.115127,1,4
1,Guru Dutt: A Tragedy in Three Acts,Arun Khopkar,"Paperback,– 7 Nov 2012",-0.593511,-0.188926,A layered portrait of a troubled genius for wh...,Cinema & Broadcast (Books),"Biographies, Diaries & True Accounts",202.93,34,Paperback,0.112130,1,1
2,Leviathan (Penguin Classics),Thomas Hobbes,"Paperback,– 25 Feb 1982",0.764977,-0.283871,"""During the time men live without a common Pow...",International Relations,Humour,299.00,28,Paperback,-0.217155,1,3
3,A Pocket Full of Rye (Miss Marple),Agatha Christie,"Paperback,– 5 Oct 2017",-0.291625,-0.200794,A handful of grain is found in the pocket of a...,Contemporary Fiction (Books),"Crime, Thriller & Mystery",180.00,34,Paperback,0.058557,-1,69
4,LIFE 70 Years of Extraordinary Photography,Editors of Life,"Hardcover,– 10 Oct 2006",1.066863,-0.343212,"For seven decades, ""Life"" has been thrilling t...",Photography Textbooks,"Arts, Film & Photography",965.62,42,Hardcover,-0.366160,1,1

In [ ]:
author_mean = df.groupby('Author')['Price'].mean()
df['Author Mean Price'] = df['Author'].map(author_mean)

In [ ]:
df.head()

,Title,Author,Edition,Reviews,Ratings,Synopsis,Genre,BookCategory,Price,Title_Length,Edition_Type,Rating_Review_Score,Synopsis Polatiry,Author Frequency,Author Mean Price
0,The Prisoner's Gold (The Hunters 3),Chris Kuzneski,"Paperback,– 10 Mar 2016",-0.442568,-0.260135,THE HUNTERS return in their third brilliant no...,Action & Adventure (Books),Action & Adventure,220.00,35,Paperback,0.115127,1,4,227.00000
1,Guru Dutt: A Tragedy in Three Acts,Arun Khopkar,"Paperback,– 7 Nov 2012",-0.593511,-0.188926,A layered portrait of a troubled genius for wh...,Cinema & Broadcast (Books),"Biographies, Diaries & True Accounts",202.93,34,Paperback,0.112130,1,1,202.93000
2,Leviathan (Penguin Classics),Thomas Hobbes,"Paperback,– 25 Feb 1982",0.764977,-0.283871,"""During the time men live without a common Pow...",International Relations,Humour,299.00,28,Paperback,-0.217155,1,3,299.00000
3,A Pocket Full of Rye (Miss Marple),Agatha Christie,"Paperback,– 5 Oct 2017",-0.291625,-0.200794,A handful of grain is found in the pocket of a...,Contemporary Fiction (Books),"Crime, Thriller & Mystery",180.00,34,Paperback,0.058557,-1,69,241.17087
4,LIFE 70 Years of Extraordinary Photography,Editors of Life,"Hardcover,– 10 Oct 2006",1.066863,-0.343212,"For seven decades, ""Life"" has been thrilling t...",Photography Textbooks,"Arts, Film & Photography",965.62,42,Hardcover,-0.366160,1,1,965.62000

In [ ]:
df.head()

,Title,Author,Edition,Reviews,Ratings,Synopsis,Genre,BookCategory,Price,Title_Length,Edition_Type,Rating_Review_Score,Synopsis Polatiry,Author Frequency,Author Mean Price
0,The Prisoner's Gold (The Hunters 3),Chris Kuzneski,"Paperback,– 10 Mar 2016",-0.442568,-0.260135,THE HUNTERS return in their third brilliant no...,Action & Adventure (Books),Action & Adventure,220.00,35,Paperback,0.115127,1,4,227.00000
1,Guru Dutt: A Tragedy in Three Acts,Arun Khopkar,"Paperback,– 7 Nov 2012",-0.593511,-0.188926,A layered portrait of a troubled genius for wh...,Cinema & Broadcast (Books),"Biographies, Diaries & True Accounts",202.93,34,Paperback,0.112130,1,1,202.93000
2,Leviathan (Penguin Classics),Thomas Hobbes,"Paperback,– 25 Feb 1982",0.764977,-0.283871,"""During the time men live without a common Pow...",International Relations,Humour,299.00,28,Paperback,-0.217155,1,3,299.00000
3,A Pocket Full of Rye (Miss Marple),Agatha Christie,"Paperback,– 5 Oct 2017",-0.291625,-0.200794,A handful of grain is found in the pocket of a...,Contemporary Fiction (Books),"Crime, Thriller & Mystery",180.00,34,Paperback,0.058557,-1,69,241.17087
4,LIFE 70 Years of Extraordinary Photography,Editors of Life,"Hardcover,– 10 Oct 2006",1.066863,-0.343212,"For seven decades, ""Life"" has been thrilling t...",Photography Textbooks,"Arts, Film & Photography",965.62,42,Hardcover,-0.366160,1,1,965.62000

In [ ]:
df.drop(['Author'],axis=1, inplace=True)

In [ ]:
df.head()

,Title,Edition,Reviews,Ratings,Synopsis,Genre,BookCategory,Price,Title_Length,Edition_Type,Rating_Review_Score,Synopsis Polatiry,Author Frequency,Author Mean Price
0,The Prisoner's Gold (The Hunters 3),"Paperback,– 10 Mar 2016",-0.442568,-0.260135,THE HUNTERS return in their third brilliant no...,Action & Adventure (Books),Action & Adventure,220.00,35,Paperback,0.115127,1,4,227.00000
1,Guru Dutt: A Tragedy in Three Acts,"Paperback,– 7 Nov 2012",-0.593511,-0.188926,A layered portrait of a troubled genius for wh...,Cinema & Broadcast (Books),"Biographies, Diaries & True Accounts",202.93,34,Paperback,0.112130,1,1,202.93000
2,Leviathan (Penguin Classics),"Paperback,– 25 Feb 1982",0.764977,-0.283871,"""During the time men live without a common Pow...",International Relations,Humour,299.00,28,Paperback,-0.217155,1,3,299.00000
3,A Pocket Full of Rye (Miss Marple),"Paperback,– 5 Oct 2017",-0.291625,-0.200794,A handful of grain is found in the pocket of a...,Contemporary Fiction (Books),"Crime, Thriller & Mystery",180.00,34,Paperback,0.058557,-1,69,241.17087
4,LIFE 70 Years of Extraordinary Photography,"Hardcover,– 10 Oct 2006",1.066863,-0.343212,"For seven decades, ""Life"" has been thrilling t...",Photography Textbooks,"Arts, Film & Photography",965.62,42,Hardcover,-0.366160,1,1,965.62000

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfIDF = TfidfVectorizer(max_features = 300, stop_words='english')

tfIDF_matrix = tfIDF.fit_transform(df['Synopsis'].fillna(""))

tfIDF_df = pd.DataFrame(tfIDF_matrix.toarray(), columns= [f"tfIDF_syn_{word}" for word in tfIDF.get_feature_names_out()])

df = pd.concat([df.reset_index(drop=True), tfIDF_df.reset_index(drop=True)], axis=1)

In [ ]:
df.head()

,Title,Edition,Reviews,Ratings,Synopsis,Genre,BookCategory,Price,Title_Length,Edition_Type,...,tfIDF_syn_works,tfIDF_syn_world,tfIDF_syn_write,tfIDF_syn_writer,tfIDF_syn_writing,tfIDF_syn_written,tfIDF_syn_year,tfIDF_syn_years,tfIDF_syn_york,tfIDF_syn_young
0,The Prisoner's Gold (The Hunters 3),"Paperback,– 10 Mar 2016",-0.442568,-0.260135,THE HUNTERS return in their third brilliant no...,Action & Adventure (Books),Action & Adventure,220.00,35,Paperback,...,0.000000,0.123801,0.0,0.0,0.218093,0.000000,0.0,0.000000,0.0,0.0
1,Guru Dutt: A Tragedy in Three Acts,"Paperback,– 7 Nov 2012",-0.593511,-0.188926,A layered portrait of a troubled genius for wh...,Cinema & Broadcast (Books),"Biographies, Diaries & True Accounts",202.93,34,Paperback,...,0.000000,0.094856,0.0,0.0,0.000000,0.147923,0.0,0.000000,0.0,0.0
2,Leviathan (Penguin Classics),"Paperback,– 25 Feb 1982",0.764977,-0.283871,"""During the time men live without a common Pow...",International Relations,Humour,299.00,28,Paperback,...,0.254643,0.132396,0.0,0.0,0.000000,0.103231,0.0,0.086341,0.0,0.0
3,A Pocket Full of Rye (Miss Marple),"Paperback,– 5 Oct 2017",-0.291625,-0.200794,A handful of grain is found in the pocket of a...,Contemporary Fiction (Books),"Crime, Thriller & Mystery",180.00,34,Paperback,...,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0
4,LIFE 70 Years of Extraordinary Photography,"Hardcover,– 10 Oct 2006",1.066863,-0.343212,"For seven decades, ""Life"" has been thrilling t...",Photography Textbooks,"Arts, Film & Photography",965.62,42,Hardcover,...,0.000000,0.156636,0.0,0.0,0.000000,0.000000,0.0,0.204298,0.0,0.0

In [ ]:
df.drop(['Title','BookCategory'],axis=1, inplace=True)

In [ ]:
df.head()

,Edition,Reviews,Ratings,Synopsis,Genre,Price,Title_Length,Edition_Type,Rating_Review_Score,Synopsis Polatiry,...,tfIDF_syn_works,tfIDF_syn_world,tfIDF_syn_write,tfIDF_syn_writer,tfIDF_syn_writing,tfIDF_syn_written,tfIDF_syn_year,tfIDF_syn_years,tfIDF_syn_york,tfIDF_syn_young
0,"Paperback,– 10 Mar 2016",-0.442568,-0.260135,THE HUNTERS return in their third brilliant no...,Action & Adventure (Books),220.00,35,Paperback,0.115127,1,...,0.000000,0.123801,0.0,0.0,0.218093,0.000000,0.0,0.000000,0.0,0.0
1,"Paperback,– 7 Nov 2012",-0.593511,-0.188926,A layered portrait of a troubled genius for wh...,Cinema & Broadcast (Books),202.93,34,Paperback,0.112130,1,...,0.000000,0.094856,0.0,0.0,0.000000,0.147923,0.0,0.000000,0.0,0.0
2,"Paperback,– 25 Feb 1982",0.764977,-0.283871,"""During the time men live without a common Pow...",International Relations,299.00,28,Paperback,-0.217155,1,...,0.254643,0.132396,0.0,0.0,0.000000,0.103231,0.0,0.086341,0.0,0.0
3,"Paperback,– 5 Oct 2017",-0.291625,-0.200794,A handful of grain is found in the pocket of a...,Contemporary Fiction (Books),180.00,34,Paperback,0.058557,-1,...,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0
4,"Hardcover,– 10 Oct 2006",1.066863,-0.343212,"For seven decades, ""Life"" has been thrilling t...",Photography Textbooks,965.62,42,Hardcover,-0.366160,1,...,0.000000,0.156636,0.0,0.0,0.000000,0.000000,0.0,0.204298,0.0,0.0

In [ ]:
df.drop(['Synopsis'],axis=1, inplace=True)

In [ ]:
df.head()

,Edition,Reviews,Ratings,Genre,Price,Title_Length,Edition_Type,Rating_Review_Score,Synopsis Polatiry,Author Frequency,...,tfIDF_syn_works,tfIDF_syn_world,tfIDF_syn_write,tfIDF_syn_writer,tfIDF_syn_writing,tfIDF_syn_written,tfIDF_syn_year,tfIDF_syn_years,tfIDF_syn_york,tfIDF_syn_young
0,"Paperback,– 10 Mar 2016",-0.442568,-0.260135,Action & Adventure (Books),220.00,35,Paperback,0.115127,1,4,...,0.000000,0.123801,0.0,0.0,0.218093,0.000000,0.0,0.000000,0.0,0.0
1,"Paperback,– 7 Nov 2012",-0.593511,-0.188926,Cinema & Broadcast (Books),202.93,34,Paperback,0.112130,1,1,...,0.000000,0.094856,0.0,0.0,0.000000,0.147923,0.0,0.000000,0.0,0.0
2,"Paperback,– 25 Feb 1982",0.764977,-0.283871,International Relations,299.00,28,Paperback,-0.217155,1,3,...,0.254643,0.132396,0.0,0.0,0.000000,0.103231,0.0,0.086341,0.0,0.0
3,"Paperback,– 5 Oct 2017",-0.291625,-0.200794,Contemporary Fiction (Books),180.00,34,Paperback,0.058557,-1,69,...,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0
4,"Hardcover,– 10 Oct 2006",1.066863,-0.343212,Photography Textbooks,965.62,42,Hardcover,-0.366160,1,1,...,0.000000,0.156636,0.0,0.0,0.000000,0.000000,0.0,0.204298,0.0,0.0

In [ ]:
gen_dummies = pd.get_dummies(df['Genre'], prefix='Genre', dtype=int)
df = pd.concat([df.drop('Genre', axis=1), gen_dummies], axis=1)

In [ ]:
df.head()

,Edition,Reviews,Ratings,Price,Title_Length,Edition_Type,Rating_Review_Score,Synopsis Polatiry,Author Frequency,Author Mean Price,...,Genre_Vocabulary Books,"Genre_Walking, Hiking & Trekking (Books)",Genre_Waste Management,"Genre_Words, Language & Grammar Reference",Genre_Workbooks,Genre_World African & Middle Eastern Literature,Genre_Writing Guides (Books),Genre_XHTML Software Programming,Genre_Young Adults' Money & Jobs (Books),Genre_Zoology
0,"Paperback,– 10 Mar 2016",-0.442568,-0.260135,220.00,35,Paperback,0.115127,1,4,227.00000,...,0,0,0,0,0,0,0,0,0,0
1,"Paperback,– 7 Nov 2012",-0.593511,-0.188926,202.93,34,Paperback,0.112130,1,1,202.93000,...,0,0,0,0,0,0,0,0,0,0
2,"Paperback,– 25 Feb 1982",0.764977,-0.283871,299.00,28,Paperback,-0.217155,1,3,299.00000,...,0,0,0,0,0,0,0,0,0,0
3,"Paperback,– 5 Oct 2017",-0.291625,-0.200794,180.00,34,Paperback,0.058557,-1,69,241.17087,...,0,0,0,0,0,0,0,0,0,0
4,"Hardcover,– 10 Oct 2006",1.066863,-0.343212,965.62,42,Hardcover,-0.366160,1,1,965.62000,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df.columns

Index(['Edition', 'Reviews', 'Ratings', 'Price', 'Title_Length',
       'Edition_Type', 'Rating_Review_Score', 'Synopsis Polatiry',
       'Author Frequency', 'Author Mean Price',
       ...
       'Genre_Vocabulary Books', 'Genre_Walking, Hiking & Trekking (Books)',
       'Genre_Waste Management', 'Genre_Words, Language & Grammar Reference',
       'Genre_Workbooks', 'Genre_World African & Middle Eastern Literature',
       'Genre_Writing Guides (Books)', 'Genre_XHTML Software Programming',
       'Genre_Young Adults' Money & Jobs (Books)', 'Genre_Zoology'],
      dtype='object', length=655)

In [ ]:
gen_dummies = pd.get_dummies(df['Edition_Type'], prefix='Edition_Type', dtype=int)
df = pd.concat([df.drop('Edition_Type',axis=1), gen_dummies], axis=1)
df.head()

,Edition,Reviews,Ratings,Price,Title_Length,Rating_Review_Score,Synopsis Polatiry,Author Frequency,Author Mean Price,tfIDF_syn_account,...,Edition_Type_Loose,Edition_Type_Mass,Edition_Type_Paperback,Edition_Type_Perfect,Edition_Type_Plastic,Edition_Type_Product,Edition_Type_Sheet,Edition_Type_SpanishPaperback,Edition_Type_Spiralbound,Edition_Type_Tankobon
0,"Paperback,– 10 Mar 2016",-0.442568,-0.260135,220.00,35,0.115127,1,4,227.00000,0.0,...,0,0,1,0,0,0,0,0,0,0
1,"Paperback,– 7 Nov 2012",-0.593511,-0.188926,202.93,34,0.112130,1,1,202.93000,0.0,...,0,0,1,0,0,0,0,0,0,0
2,"Paperback,– 25 Feb 1982",0.764977,-0.283871,299.00,28,-0.217155,1,3,299.00000,0.0,...,0,0,1,0,0,0,0,0,0,0
3,"Paperback,– 5 Oct 2017",-0.291625,-0.200794,180.00,34,0.058557,-1,69,241.17087,0.0,...,0,0,1,0,0,0,0,0,0,0
4,"Hardcover,– 10 Oct 2006",1.066863,-0.343212,965.62,42,-0.366160,1,1,965.62000,0.0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df.drop('Edition',axis=1,inplace=True)
df.head()

,Reviews,Ratings,Price,Title_Length,Rating_Review_Score,Synopsis Polatiry,Author Frequency,Author Mean Price,tfIDF_syn_account,tfIDF_syn_action,...,Edition_Type_Loose,Edition_Type_Mass,Edition_Type_Paperback,Edition_Type_Perfect,Edition_Type_Plastic,Edition_Type_Product,Edition_Type_Sheet,Edition_Type_SpanishPaperback,Edition_Type_Spiralbound,Edition_Type_Tankobon
0,-0.442568,-0.260135,220.00,35,0.115127,1,4,227.00000,0.0,0.251391,...,0,0,1,0,0,0,0,0,0,0
1,-0.593511,-0.188926,202.93,34,0.112130,1,1,202.93000,0.0,0.000000,...,0,0,1,0,0,0,0,0,0,0
2,0.764977,-0.283871,299.00,28,-0.217155,1,3,299.00000,0.0,0.000000,...,0,0,1,0,0,0,0,0,0,0
3,-0.291625,-0.200794,180.00,34,0.058557,-1,69,241.17087,0.0,0.000000,...,0,0,1,0,0,0,0,0,0,0
4,1.066863,-0.343212,965.62,42,-0.366160,1,1,965.62000,0.0,0.000000,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df.head()

,Reviews,Ratings,Price,Title_Length,Rating_Review_Score,Synopsis Polatiry,Author Frequency,Author Mean Price,tfIDF_syn_account,tfIDF_syn_action,...,Edition_Type_Loose,Edition_Type_Mass,Edition_Type_Paperback,Edition_Type_Perfect,Edition_Type_Plastic,Edition_Type_Product,Edition_Type_Sheet,Edition_Type_SpanishPaperback,Edition_Type_Spiralbound,Edition_Type_Tankobon
0,-0.442568,-0.260135,220.00,35,0.115127,1,4,227.00000,0.0,0.251391,...,0,0,1,0,0,0,0,0,0,0
1,-0.593511,-0.188926,202.93,34,0.112130,1,1,202.93000,0.0,0.000000,...,0,0,1,0,0,0,0,0,0,0
2,0.764977,-0.283871,299.00,28,-0.217155,1,3,299.00000,0.0,0.000000,...,0,0,1,0,0,0,0,0,0,0
3,-0.291625,-0.200794,180.00,34,0.058557,-1,69,241.17087,0.0,0.000000,...,0,0,1,0,0,0,0,0,0,0
4,1.066863,-0.343212,965.62,42,-0.366160,1,1,965.62000,0.0,0.000000,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
#check if there is any non-number columns left in the data
non_numeric_cols = df.select_dtypes(exclude=['number']).columns.tolist()
print("Non-numeric columns:", non_numeric_cols)

Non-numeric columns: []

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.impute import SimpleImputer

df1 = df.copy()

X = df1.drop(columns=['Price'])
y = df1['Price']

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

imp = SimpleImputer(strategy="mean")

X_train = imp.fit_transform(X_train)
X_test = imp.transform(X_test)


lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

y_pred = lr_model.predict(X_test)

#Evaluation
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test,y_pred)


print(f"RMSE: {rmse:.2f}")
print(f"r2_score: {r2:.3f}")

RMSE: 314.08
r2_score: 0.771

In [ ]:
X_train.isna().sum()

Reviews                           0
Ratings                          20
Title_Length                      0
Rating_Review_Score              20
Synopsis Polatiry                 0
                                 ..
Edition_Type_Product              0
Edition_Type_Sheet                0
Edition_Type_SpanishPaperback     0
Edition_Type_Spiralbound          0
Edition_Type_Tankobon             0
Length: 671, dtype: int64